//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoomsManagement.DAL.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBoilerProcess
    {
        public tblBoilerProcess()
        {
            this.tblBemProcessDetails = new HashSet<tblBemProcessDetail>();
            this.tblBolierProcessDetails = new HashSet<tblBolierProcessDetail>();
        }
    
        public long BolierProcessID { get; set; }
        public Nullable<long> MachineID { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public string Shift { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<double> Tempreture { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdationDateTime { get; set; }
        public Nullable<System.DateTime> CreationDateTIme { get; set; }
    
        public virtual ICollection<tblBemProcessDetail> tblBemProcessDetails { get; set; }
        public virtual ICollection<tblBolierProcessDetail> tblBolierProcessDetails { get; set; }
    }
}
