//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoomsManagement.DAL.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompanyMachineMST
    {
        public long RowId { get; set; }
        public long MachineId { get; set; }
        public long CompanyId { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblMachineMST tblMachineMST { get; set; }
    }
}
