//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoomsManagement.DAL.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductQualityMST
    {
        public long ProductQualityID { get; set; }
        public string ProductQualityName { get; set; }
        public Nullable<double> WARPDenierAfterTPM { get; set; }
        public Nullable<int> WARPNumberOfFilaments { get; set; }
        public Nullable<int> WARPYarnQualityID { get; set; }
        public Nullable<int> WARPYarnTypeID { get; set; }
        public string WARPDirectionOfTwistS { get; set; }
        public string WARPDirectionOfTwistZ { get; set; }
        public Nullable<int> WARPTwistPerMeterS { get; set; }
        public Nullable<int> WARPTwistPerMeterZ { get; set; }
        public Nullable<double> WEFTDenierAfterTPM { get; set; }
        public Nullable<int> WEFTNumberOfFilaments1 { get; set; }
        public Nullable<int> WEFTYarnQualityID { get; set; }
        public Nullable<int> WEFTYarnTypeID { get; set; }
        public string WEFTDirectionOfTwistS { get; set; }
        public string WEFTDirectionOfTwistZ { get; set; }
        public Nullable<int> WEFTTwistPerMeterS { get; set; }
        public Nullable<int> WEFTTwistPerMeterZ { get; set; }
        public Nullable<int> ApproxTotalEndsWithBorder { get; set; }
        public Nullable<double> ReedOnLoom { get; set; }
        public Nullable<double> PickOnLoom { get; set; }
        public Nullable<double> Border { get; set; }
        public string HeatSetting { get; set; }
        public Nullable<double> WeightOfFabricWARP { get; set; }
        public Nullable<double> WeightOfFabricWEFT { get; set; }
        public Nullable<double> TotalWeight { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
    }
}
