//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoomsManagement.DAL.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblYarnPurchaseItem
    {
        public tblYarnPurchaseItem()
        {
            this.tblWindingWorks = new HashSet<tblWindingWork>();
        }
    
        public long PurchaseItemID { get; set; }
        public Nullable<long> PurchaseID { get; set; }
        public Nullable<long> YarnID { get; set; }
        public Nullable<long> YarnPackageTypeID { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string BoxNo { get; set; }
        public Nullable<double> GrossWeight { get; set; }
        public Nullable<double> TareWeight { get; set; }
        public Nullable<double> NetWeight { get; set; }
        public Nullable<double> Cheese { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public Nullable<long> YarnQualityID { get; set; }
        public Nullable<long> YarnTypeID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdationDateTime { get; set; }
        public Nullable<System.DateTime> CreationDateTIme { get; set; }
    
        public virtual ICollection<tblWindingWork> tblWindingWorks { get; set; }
        public virtual tblYarnPackageType tblYarnPackageType { get; set; }
        public virtual tblYarnPurchase tblYarnPurchase { get; set; }
        public virtual tblYarnQualityMST tblYarnQualityMST { get; set; }
        public virtual tblYarnQualityMST tblYarnQualityMST1 { get; set; }
        public virtual tblYarnTypeMST tblYarnTypeMST { get; set; }
    }
}
