//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-09 - 14:23:34
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace LoomsManagement.Domain.DTO
{
    [DataContract()]
    public partial class tblAttendanceMSTDTO
    {
        [DataMember()]
        public Int64 AttendanceID { get; set; }

        [DataMember()]
        public Nullable<Int64> EmployeeID { get; set; }

        [DataMember()]
        public Nullable<DateTime> StartTime { get; set; }

        [DataMember()]
        public Nullable<DateTime> EndTime { get; set; }

        [DataMember()]
        public Nullable<Double> MeterWorked { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsActive { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsDelete { get; set; }

        [DataMember()]
        public Nullable<Int32> CreateBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreationDateTime { get; set; }

        [DataMember()]
        public Nullable<Int32> UpdateBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> UpdationDateTime { get; set; }

        [DataMember()]
        public Int64 tblEmployee_EmployeeID { get; set; }

        public tblAttendanceMSTDTO()
        {
        }

        public tblAttendanceMSTDTO(Int64 attendanceID, Nullable<Int64> employeeID, Nullable<DateTime> startTime, Nullable<DateTime> endTime, Nullable<Double> meterWorked, Nullable<Boolean> isActive, Nullable<Boolean> isDelete, Nullable<Int32> createBy, Nullable<DateTime> creationDateTime, Nullable<Int32> updateBy, Nullable<DateTime> updationDateTime, Int64 tblEmployee_EmployeeID)
        {
			this.AttendanceID = attendanceID;
			this.EmployeeID = employeeID;
			this.StartTime = startTime;
			this.EndTime = endTime;
			this.MeterWorked = meterWorked;
			this.IsActive = isActive;
			this.IsDelete = isDelete;
			this.CreateBy = createBy;
			this.CreationDateTime = creationDateTime;
			this.UpdateBy = updateBy;
			this.UpdationDateTime = updationDateTime;
			this.tblEmployee_EmployeeID = tblEmployee_EmployeeID;
        }
    }
}
