//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-24 - 22:25:30
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace LoomsManagement.Domain.DTO
{
    [DataContract()]
    public partial class tblBeamMSTDTO
    {
        [DataMember()]
        public Int64 BeemID { get; set; }

        [DataMember()]
        public Nullable<Int64> CompanyID { get; set; }

        [DataMember()]
        public Nullable<Int32> WrapperPartyName { get; set; }

        [DataMember()]
        public Nullable<Int32> JobberPartyName { get; set; }

        [DataMember()]
        public Nullable<DateTime> BeemDate { get; set; }

        [DataMember()]
        public Nullable<Int32> YarnQuality { get; set; }

        [DataMember()]
        public Nullable<Int32> GrayQuality { get; set; }

        [DataMember()]
        public Nullable<Int32> TarNo { get; set; }

        [DataMember()]
        public Nullable<Double> Meters { get; set; }

        [DataMember()]
        public Nullable<Int32> Taka { get; set; }

        [DataMember()]
        public Nullable<Double> Weight { get; set; }

        [DataMember()]
        public Nullable<Double> ProductionMeters { get; set; }

        [DataMember()]
        public Nullable<Int32> ProductionTaka { get; set; }

        [DataMember()]
        public Nullable<Double> PipeWeight { get; set; }

        [DataMember()]
        public Nullable<DateTime> LoadingDate { get; set; }

        [DataMember()]
        public Nullable<Double> MinStrategy { get; set; }

        [DataMember()]
        public Nullable<Int32> MachineNo { get; set; }

        [DataMember()]
        public String Remarks { get; set; }

        [DataMember()]
        public Nullable<Boolean> BhidanStatus { get; set; }

        [DataMember()]
        public Nullable<DateTime> BhidanDate { get; set; }

        [DataMember()]
        public Nullable<Int32> PasaraiName { get; set; }

        [DataMember()]
        public Nullable<Double> Count { get; set; }

        [DataMember()]
        public Nullable<DateTime> IssueDate { get; set; }

        [DataMember()]
        public Nullable<Boolean> TakaMeter { get; set; }

        [DataMember()]
        public Nullable<Double> Rate { get; set; }

        [DataMember()]
        public Nullable<Double> Amount { get; set; }

        [DataMember()]
        public Nullable<Double> MeterConsumption { get; set; }

        [DataMember()]
        public Nullable<Double> RPM { get; set; }

        [DataMember()]
        public Nullable<Double> Pick { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsDelete { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsActive { get; set; }

        [DataMember()]
        public Nullable<Int32> CreatedBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreationDateTime { get; set; }

        [DataMember()]
        public Nullable<Int32> UpdateBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> UpdationDateTime { get; set; }

        public tblBeamMSTDTO()
        {
        }

        public tblBeamMSTDTO(Int64 beemID, Nullable<Int64> companyID, Nullable<Int32> wrapperPartyName, Nullable<Int32> jobberPartyName, Nullable<DateTime> beemDate, Nullable<Int32> yarnQuality, Nullable<Int32> grayQuality, Nullable<Int32> tarNo, Nullable<Double> meters, Nullable<Int32> taka, Nullable<Double> weight, Nullable<Double> productionMeters, Nullable<Int32> productionTaka, Nullable<Double> pipeWeight, Nullable<DateTime> loadingDate, Nullable<Double> minStrategy, Nullable<Int32> machineNo, String remarks, Nullable<Boolean> bhidanStatus, Nullable<DateTime> bhidanDate, Nullable<Int32> pasaraiName, Nullable<Double> count, Nullable<DateTime> issueDate, Nullable<Boolean> takaMeter, Nullable<Double> rate, Nullable<Double> amount, Nullable<Double> meterConsumption, Nullable<Double> rPM, Nullable<Double> pick, Nullable<Boolean> isDelete, Nullable<Boolean> isActive, Nullable<Int32> createdBy, Nullable<DateTime> creationDateTime, Nullable<Int32> updateBy, Nullable<DateTime> updationDateTime)
        {
			this.BeemID = beemID;
			this.CompanyID = companyID;
			this.WrapperPartyName = wrapperPartyName;
			this.JobberPartyName = jobberPartyName;
			this.BeemDate = beemDate;
			this.YarnQuality = yarnQuality;
			this.GrayQuality = grayQuality;
			this.TarNo = tarNo;
			this.Meters = meters;
			this.Taka = taka;
			this.Weight = weight;
			this.ProductionMeters = productionMeters;
			this.ProductionTaka = productionTaka;
			this.PipeWeight = pipeWeight;
			this.LoadingDate = loadingDate;
			this.MinStrategy = minStrategy;
			this.MachineNo = machineNo;
			this.Remarks = remarks;
			this.BhidanStatus = bhidanStatus;
			this.BhidanDate = bhidanDate;
			this.PasaraiName = pasaraiName;
			this.Count = count;
			this.IssueDate = issueDate;
			this.TakaMeter = takaMeter;
			this.Rate = rate;
			this.Amount = amount;
			this.MeterConsumption = meterConsumption;
			this.RPM = rPM;
			this.Pick = pick;
			this.IsDelete = isDelete;
			this.IsActive = isActive;
			this.CreatedBy = createdBy;
			this.CreationDateTime = creationDateTime;
			this.UpdateBy = updateBy;
			this.UpdationDateTime = updationDateTime;
        }
    }
}
