//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-09 - 14:23:37
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace LoomsManagement.Domain.DTO
{
    [DataContract()]
    public partial class tblBranchMSTDTO
    {
        [DataMember()]
        public Int64 BranchID { get; set; }

        [DataMember()]
        public String BranchName { get; set; }

        [DataMember()]
        public String Address { get; set; }

        [DataMember()]
        public Nullable<Int64> BankID { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsDelete { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsActive { get; set; }

        [DataMember()]
        public Nullable<Int32> CreateBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreationDateTime { get; set; }

        [DataMember()]
        public Nullable<Int32> UpdateBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> UpdationDateTime { get; set; }

        [DataMember()]
        public Int64 tblBankMST_BankID { get; set; }

        public tblBranchMSTDTO()
        {
        }

        public tblBranchMSTDTO(Int64 branchID, String branchName, String address, Nullable<Int64> bankID, Nullable<Boolean> isDelete, Nullable<Boolean> isActive, Nullable<Int32> createBy, Nullable<DateTime> creationDateTime, Nullable<Int32> updateBy, Nullable<DateTime> updationDateTime, Int64 tblBankMST_BankID)
        {
			this.BranchID = branchID;
			this.BranchName = branchName;
			this.Address = address;
			this.BankID = bankID;
			this.IsDelete = isDelete;
			this.IsActive = isActive;
			this.CreateBy = createBy;
			this.CreationDateTime = creationDateTime;
			this.UpdateBy = updateBy;
			this.UpdationDateTime = updationDateTime;
			this.tblBankMST_BankID = tblBankMST_BankID;
        }
    }
}
