//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-09 - 14:23:36
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace LoomsManagement.Domain.DTO
{
    [DataContract()]
    public partial class tblBemProcessDetailDTO
    {
        [DataMember()]
        public Int64 BemProcessDetailsID { get; set; }

        [DataMember()]
        public Nullable<Int64> BemProcessID { get; set; }

        [DataMember()]
        public Nullable<Int64> TFORoleProcessID { get; set; }

        [DataMember()]
        public Nullable<Int32> IssueNoOFCopes { get; set; }

        [DataMember()]
        public Nullable<Double> IssueWeights { get; set; }

        [DataMember()]
        public Nullable<Int64> YarnQualityID { get; set; }

        [DataMember()]
        public Nullable<Int64> YarnTypeID { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsDelete { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsActive { get; set; }

        [DataMember()]
        public Nullable<Int32> CreateBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreationDateTime { get; set; }

        [DataMember()]
        public Nullable<Int32> UpdateBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> UpdationDateTime { get; set; }

        [DataMember()]
        public Int64 tblBeemProcess_BeemProcessID { get; set; }

        [DataMember()]
        public Int64 tblBoilerProcess_BolierProcessID { get; set; }

        [DataMember()]
        public Int64 tblTFOProcess_TFORoleProcessId { get; set; }

        public tblBemProcessDetailDTO()
        {
        }

        public tblBemProcessDetailDTO(Int64 bemProcessDetailsID, Nullable<Int64> bemProcessID, Nullable<Int64> tFORoleProcessID, Nullable<Int32> issueNoOFCopes, Nullable<Double> issueWeights, Nullable<Int64> yarnQualityID, Nullable<Int64> yarnTypeID, Nullable<Boolean> isDelete, Nullable<Boolean> isActive, Nullable<Int32> createBy, Nullable<DateTime> creationDateTime, Nullable<Int32> updateBy, Nullable<DateTime> updationDateTime, Int64 tblBeemProcess_BeemProcessID, Int64 tblBoilerProcess_BolierProcessID, Int64 tblTFOProcess_TFORoleProcessId)
        {
			this.BemProcessDetailsID = bemProcessDetailsID;
			this.BemProcessID = bemProcessID;
			this.TFORoleProcessID = tFORoleProcessID;
			this.IssueNoOFCopes = issueNoOFCopes;
			this.IssueWeights = issueWeights;
			this.YarnQualityID = yarnQualityID;
			this.YarnTypeID = yarnTypeID;
			this.IsDelete = isDelete;
			this.IsActive = isActive;
			this.CreateBy = createBy;
			this.CreationDateTime = creationDateTime;
			this.UpdateBy = updateBy;
			this.UpdationDateTime = updationDateTime;
			this.tblBeemProcess_BeemProcessID = tblBeemProcess_BeemProcessID;
			this.tblBoilerProcess_BolierProcessID = tblBoilerProcess_BolierProcessID;
			this.tblTFOProcess_TFORoleProcessId = tblTFOProcess_TFORoleProcessId;
        }
    }
}
