//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-09 - 14:23:38
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace LoomsManagement.Domain.DTO
{
    [DataContract()]
    public partial class tblBrokersMSTDTO
    {
        [DataMember()]
        public Int64 BrokerID { get; set; }

        [DataMember()]
        public String BrokerName { get; set; }

        [DataMember()]
        public String BrokerFirmName { get; set; }

        [DataMember()]
        public String Address { get; set; }

        [DataMember()]
        public String ContactNo { get; set; }

        [DataMember()]
        public String MobileNo { get; set; }

        [DataMember()]
        public String DealingIn { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsDelete { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsActive { get; set; }

        [DataMember()]
        public Nullable<Int32> CreateBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreationDateTime { get; set; }

        [DataMember()]
        public Nullable<Int32> UpdateBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> UpdationDateTime { get; set; }

        public tblBrokersMSTDTO()
        {
        }

        public tblBrokersMSTDTO(Int64 brokerID, String brokerName, String brokerFirmName, String address, String contactNo, String mobileNo, String dealingIn, Nullable<Boolean> isDelete, Nullable<Boolean> isActive, Nullable<Int32> createBy, Nullable<DateTime> creationDateTime, Nullable<Int32> updateBy, Nullable<DateTime> updationDateTime)
        {
			this.BrokerID = brokerID;
			this.BrokerName = brokerName;
			this.BrokerFirmName = brokerFirmName;
			this.Address = address;
			this.ContactNo = contactNo;
			this.MobileNo = mobileNo;
			this.DealingIn = dealingIn;
			this.IsDelete = isDelete;
			this.IsActive = isActive;
			this.CreateBy = createBy;
			this.CreationDateTime = creationDateTime;
			this.UpdateBy = updateBy;
			this.UpdationDateTime = updationDateTime;
        }
    }
}
