//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-09 - 14:23:35
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace LoomsManagement.Domain.DTO
{
    [DataContract()]
    public partial class tblBeemProcessDTO
    {
        [DataMember()]
        public Int64 BeemProcessID { get; set; }

        [DataMember()]
        public Nullable<Int64> MachineID { get; set; }

        [DataMember()]
        public Nullable<Int64> EmployeeID { get; set; }

        [DataMember()]
        public String Shift { get; set; }

        [DataMember()]
        public Nullable<DateTime> StartDateTime { get; set; }

        [DataMember()]
        public Nullable<DateTime> EndDateTime { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsDelete { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsActive { get; set; }

        [DataMember()]
        public Nullable<Int32> CreateBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreationDateTime { get; set; }

        [DataMember()]
        public Nullable<Int32> UpdateBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> UpdationDateTime { get; set; }

        [DataMember()]
        public List<Int64> tblBemProcessDetails_BemProcessDetailsID { get; set; }

        public tblBeemProcessDTO()
        {
        }

        public tblBeemProcessDTO(Int64 beemProcessID, Nullable<Int64> machineID, Nullable<Int64> employeeID, String shift, Nullable<DateTime> startDateTime, Nullable<DateTime> endDateTime, Nullable<Boolean> isDelete, Nullable<Boolean> isActive, Nullable<Int32> createBy, Nullable<DateTime> creationDateTime, Nullable<Int32> updateBy, Nullable<DateTime> updationDateTime, List<Int64> tblBemProcessDetails_BemProcessDetailsID)
        {
			this.BeemProcessID = beemProcessID;
			this.MachineID = machineID;
			this.EmployeeID = employeeID;
			this.Shift = shift;
			this.StartDateTime = startDateTime;
			this.EndDateTime = endDateTime;
			this.IsDelete = isDelete;
			this.IsActive = isActive;
			this.CreateBy = createBy;
			this.CreationDateTime = creationDateTime;
			this.UpdateBy = updateBy;
			this.UpdationDateTime = updationDateTime;
			this.tblBemProcessDetails_BemProcessDetailsID = tblBemProcessDetails_BemProcessDetailsID;
        }
    }
}
