//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-28 - 10:51:01
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace LoomsManagement.Domain.DTO
{
    [DataContract()]
    public partial class tblBeamMSTDTO
    {
        [DataMember()]
        public Int64 BeemID { get; set; }

        [DataMember()]
        public Nullable<Int64> CompanyID { get; set; }

        [DataMember()]
        public String BeamNo { get; set; }

        [DataMember()]
        public Nullable<Int64> WrapperPartyID { get; set; }

        [DataMember()]
        public Nullable<Int32> JobberPartyName { get; set; }

        [DataMember()]
        public Nullable<DateTime> BeemDate { get; set; }

        [DataMember()]
        public Nullable<Int32> YarnQualityID { get; set; }

        [DataMember()]
        public Nullable<Int32> GrayQualityId { get; set; }

        [DataMember()]
        public String LotNo { get; set; }

        [DataMember()]
        public Nullable<Int32> NoofTar { get; set; }

        [DataMember()]
        public Nullable<Double> Meters { get; set; }

        [DataMember()]
        public Nullable<Int32> Taka { get; set; }

        [DataMember()]
        public Nullable<Double> GrossWeight { get; set; }

        [DataMember()]
        public Nullable<Double> NetWeight { get; set; }

        [DataMember()]
        public Nullable<DateTime> LoadingDate { get; set; }

        [DataMember()]
        public Nullable<Boolean> BhidanStatus { get; set; }

        [DataMember()]
        public Nullable<DateTime> BhidanDate { get; set; }

        [DataMember()]
        public Nullable<Int32> PasaraiEmployeeId { get; set; }

        [DataMember()]
        public Nullable<Double> ProductionMeters { get; set; }

        [DataMember()]
        public Nullable<Int32> ProductionTaka { get; set; }

        [DataMember()]
        public Nullable<Double> PipeWeight { get; set; }

        [DataMember()]
        public Nullable<Double> MinStrategy { get; set; }

        [DataMember()]
        public Nullable<Int64> MachineId { get; set; }

        [DataMember()]
        public String Remarks { get; set; }

        [DataMember()]
        public Nullable<DateTime> IssueDate { get; set; }

        [DataMember()]
        public Nullable<Boolean> TakaMeter { get; set; }

        [DataMember()]
        public Nullable<Double> Rate { get; set; }

        [DataMember()]
        public Nullable<Double> Amount { get; set; }

        [DataMember()]
        public Nullable<Double> MeterConsumption { get; set; }

        [DataMember()]
        public Nullable<Double> RPM { get; set; }

        [DataMember()]
        public Nullable<Double> Pick { get; set; }

        [DataMember()]
        public Nullable<Double> My { get; set; }

        [DataMember()]
        public Nullable<Double> FinalAmount { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsDelete { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsActive { get; set; }

        [DataMember()]
        public Nullable<Int32> CreatedBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreationDateTime { get; set; }

        [DataMember()]
        public Nullable<Int32> UpdateBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> UpdationDateTime { get; set; }

        [DataMember()]
        public Int64 tblBeamMST1_BeemID { get; set; }

        [DataMember()]
        public Int64 tblBeamMST2_BeemID { get; set; }

        public tblBeamMSTDTO()
        {
        }

        public tblBeamMSTDTO(Int64 beemID, Nullable<Int64> companyID, String beamNo, Nullable<Int64> wrapperPartyID, Nullable<Int32> jobberPartyName, Nullable<DateTime> beemDate, Nullable<Int32> yarnQualityID, Nullable<Int32> grayQualityId, String lotNo, Nullable<Int32> noofTar, Nullable<Double> meters, Nullable<Int32> taka, Nullable<Double> grossWeight, Nullable<Double> netWeight, Nullable<DateTime> loadingDate, Nullable<Boolean> bhidanStatus, Nullable<DateTime> bhidanDate, Nullable<Int32> pasaraiEmployeeId, Nullable<Double> productionMeters, Nullable<Int32> productionTaka, Nullable<Double> pipeWeight, Nullable<Double> minStrategy, Nullable<Int64> machineId, String remarks, Nullable<DateTime> issueDate, Nullable<Boolean> takaMeter, Nullable<Double> rate, Nullable<Double> amount, Nullable<Double> meterConsumption, Nullable<Double> rPM, Nullable<Double> pick, Nullable<Double> my, Nullable<Double> finalAmount, Nullable<Boolean> isDelete, Nullable<Boolean> isActive, Nullable<Int32> createdBy, Nullable<DateTime> creationDateTime, Nullable<Int32> updateBy, Nullable<DateTime> updationDateTime, Int64 tblBeamMST1_BeemID, Int64 tblBeamMST2_BeemID)
        {
			this.BeemID = beemID;
			this.CompanyID = companyID;
			this.BeamNo = beamNo;
			this.WrapperPartyID = wrapperPartyID;
			this.JobberPartyName = jobberPartyName;
			this.BeemDate = beemDate;
			this.YarnQualityID = yarnQualityID;
			this.GrayQualityId = grayQualityId;
			this.LotNo = lotNo;
			this.NoofTar = noofTar;
			this.Meters = meters;
			this.Taka = taka;
			this.GrossWeight = grossWeight;
			this.NetWeight = netWeight;
			this.LoadingDate = loadingDate;
			this.BhidanStatus = bhidanStatus;
			this.BhidanDate = bhidanDate;
			this.PasaraiEmployeeId = pasaraiEmployeeId;
			this.ProductionMeters = productionMeters;
			this.ProductionTaka = productionTaka;
			this.PipeWeight = pipeWeight;
			this.MinStrategy = minStrategy;
			this.MachineId = machineId;
			this.Remarks = remarks;
			this.IssueDate = issueDate;
			this.TakaMeter = takaMeter;
			this.Rate = rate;
			this.Amount = amount;
			this.MeterConsumption = meterConsumption;
			this.RPM = rPM;
			this.Pick = pick;
			this.My = my;
			this.FinalAmount = finalAmount;
			this.IsDelete = isDelete;
			this.IsActive = isActive;
			this.CreatedBy = createdBy;
			this.CreationDateTime = creationDateTime;
			this.UpdateBy = updateBy;
			this.UpdationDateTime = updationDateTime;
			this.tblBeamMST1_BeemID = tblBeamMST1_BeemID;
			this.tblBeamMST2_BeemID = tblBeamMST2_BeemID;
        }
    }
}
