//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-09 - 14:23:34
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace LoomsManagement.Domain.DTO
{
    [DataContract()]
    public partial class tblBankMSTDTO
    {
        [DataMember()]
        public Int64 BankID { get; set; }

        [DataMember()]
        public String BankName { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsDelete { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsActive { get; set; }

        [DataMember()]
        public Nullable<Int32> CreateBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreationDateTime { get; set; }

        [DataMember()]
        public Nullable<Int32> UpdateBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> UpdationDateTime { get; set; }

        [DataMember()]
        public List<Int64> tblBranchMSTs_BranchID { get; set; }

        public tblBankMSTDTO()
        {
        }

        public tblBankMSTDTO(Int64 bankID, String bankName, Nullable<Boolean> isDelete, Nullable<Boolean> isActive, Nullable<Int32> createBy, Nullable<DateTime> creationDateTime, Nullable<Int32> updateBy, Nullable<DateTime> updationDateTime, List<Int64> tblBranchMSTs_BranchID)
        {
			this.BankID = bankID;
			this.BankName = bankName;
			this.IsDelete = isDelete;
			this.IsActive = isActive;
			this.CreateBy = createBy;
			this.CreationDateTime = creationDateTime;
			this.UpdateBy = updateBy;
			this.UpdationDateTime = updationDateTime;
			this.tblBranchMSTs_BranchID = tblBranchMSTs_BranchID;
        }
    }
}
