//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-09 - 14:23:38
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace LoomsManagement.Domain.DTO
{
    [DataContract()]
    public partial class tblCompanyDTO
    {
        [DataMember()]
        public Int64 CompanyID { get; set; }

        [DataMember()]
        public String CompanyName { get; set; }

        [DataMember()]
        public String ComapnyCode { get; set; }

        [DataMember()]
        public String OwnerName { get; set; }

        [DataMember()]
        public Nullable<DateTime> StartDate { get; set; }

        [DataMember()]
        public String Address { get; set; }

        [DataMember()]
        public String ContactPersonName { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreationDate { get; set; }

        [DataMember()]
        public Nullable<Double> InvestmentAmount { get; set; }

        [DataMember()]
        public String PANNo { get; set; }

        [DataMember()]
        public String CSTNo { get; set; }

        [DataMember()]
        public String ECCNo { get; set; }

        [DataMember()]
        public String SMSNO { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsActive { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsDelete { get; set; }

        [DataMember()]
        public Nullable<Int32> CreatedBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreatedDateTime { get; set; }

        [DataMember()]
        public Nullable<Int32> UpdatedBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> UpdatedDateTime { get; set; }

        [DataMember()]
        public List<Int64> tblCompanyMachineMSTs_RowId { get; set; }

        public tblCompanyDTO()
        {
        }

        public tblCompanyDTO(Int64 companyID, String companyName, String comapnyCode, String ownerName, Nullable<DateTime> startDate, String address, String contactPersonName, Nullable<DateTime> creationDate, Nullable<Double> investmentAmount, String pANNo, String cSTNo, String eCCNo, String sMSNO, Nullable<Boolean> isActive, Nullable<Boolean> isDelete, Nullable<Int32> createdBy, Nullable<DateTime> createdDateTime, Nullable<Int32> updatedBy, Nullable<DateTime> updatedDateTime, List<Int64> tblCompanyMachineMSTs_RowId)
        {
			this.CompanyID = companyID;
			this.CompanyName = companyName;
			this.ComapnyCode = comapnyCode;
			this.OwnerName = ownerName;
			this.StartDate = startDate;
			this.Address = address;
			this.ContactPersonName = contactPersonName;
			this.CreationDate = creationDate;
			this.InvestmentAmount = investmentAmount;
			this.PANNo = pANNo;
			this.CSTNo = cSTNo;
			this.ECCNo = eCCNo;
			this.SMSNO = sMSNO;
			this.IsActive = isActive;
			this.IsDelete = isDelete;
			this.CreatedBy = createdBy;
			this.CreatedDateTime = createdDateTime;
			this.UpdatedBy = updatedBy;
			this.UpdatedDateTime = updatedDateTime;
			this.tblCompanyMachineMSTs_RowId = tblCompanyMachineMSTs_RowId;
        }
    }
}
