//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-09 - 14:23:39
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace LoomsManagement.Domain.DTO
{
    [DataContract()]
    public partial class tblCompanyMachineMSTDTO
    {
        [DataMember()]
        public Int64 RowId { get; set; }

        [DataMember()]
        public Int64 MachineId { get; set; }

        [DataMember()]
        public Int64 CompanyId { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsDelete { get; set; }

        [DataMember()]
        public Int64 tblCompany_CompanyID { get; set; }

        [DataMember()]
        public Int64 tblMachineMST_MachineID { get; set; }

        public tblCompanyMachineMSTDTO()
        {
        }

        public tblCompanyMachineMSTDTO(Int64 rowId, Int64 machineId, Int64 companyId, Nullable<Boolean> isDelete, Int64 tblCompany_CompanyID, Int64 tblMachineMST_MachineID)
        {
			this.RowId = rowId;
			this.MachineId = machineId;
			this.CompanyId = companyId;
			this.IsDelete = isDelete;
			this.tblCompany_CompanyID = tblCompany_CompanyID;
			this.tblMachineMST_MachineID = tblMachineMST_MachineID;
        }
    }
}
