//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-09 - 14:23:40
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace LoomsManagement.Domain.DTO
{
    [DataContract()]
    public partial class tblEmployeeDTO
    {
        [DataMember()]
        public Int64 EmployeeID { get; set; }

        [DataMember()]
        public Nullable<Int64> EmployeeTypeID { get; set; }

        [DataMember()]
        public String EmployeeCode { get; set; }

        [DataMember()]
        public String JobTitle { get; set; }

        [DataMember()]
        public String FirstName { get; set; }

        [DataMember()]
        public String MiddleName { get; set; }

        [DataMember()]
        public String LastName { get; set; }

        [DataMember()]
        public String ResidentialAddress { get; set; }

        [DataMember()]
        public String PermanentAddress { get; set; }

        [DataMember()]
        public String MobileNo { get; set; }

        [DataMember()]
        public String EmailID { get; set; }

        [DataMember()]
        public Nullable<DateTime> DOB { get; set; }

        [DataMember()]
        public String Gender { get; set; }

        [DataMember()]
        public String IDProfe { get; set; }

        [DataMember()]
        public String IDProfeNo { get; set; }

        [DataMember()]
        public Byte[] Photo { get; set; }

        [DataMember()]
        public Nullable<DateTime> JoinDate { get; set; }

        [DataMember()]
        public Nullable<DateTime> LeaveDate { get; set; }

        [DataMember()]
        public Nullable<Int32> SponsorsID { get; set; }

        [DataMember()]
        public String Shift { get; set; }

        [DataMember()]
        public Nullable<Double> Salary { get; set; }

        [DataMember()]
        public Nullable<Double> PerDayWorkingHours { get; set; }

        [DataMember()]
        public Nullable<Double> PerHourSalary { get; set; }

        [DataMember()]
        public Nullable<Boolean> PaymentType { get; set; }

        [DataMember()]
        public String BankName { get; set; }

        [DataMember()]
        public String BranchName { get; set; }

        [DataMember()]
        public String AccountNo { get; set; }

        [DataMember()]
        public String RTGSNo { get; set; }

        [DataMember()]
        public String IFSCCode { get; set; }

        [DataMember()]
        public Nullable<Double> OpeningBalance { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsDelete { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsActive { get; set; }

        [DataMember()]
        public Nullable<Int32> CreatedBY { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreatedDate { get; set; }

        [DataMember()]
        public Nullable<Int32> UpdatedBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> UpdatedDate { get; set; }

        [DataMember()]
        public List<Int64> tblAttendanceMSTs_AttendanceID { get; set; }

        [DataMember()]
        public Int64 tblEmployeeTypeMST_EmployeeTypeID { get; set; }

        [DataMember()]
        public List<Int32> tblSalaryMSTs_SalaryID { get; set; }

        public tblEmployeeDTO()
        {
        }

        public tblEmployeeDTO(Int64 employeeID, Nullable<Int64> employeeTypeID, String employeeCode, String jobTitle, String firstName, String middleName, String lastName, String residentialAddress, String permanentAddress, String mobileNo, String emailID, Nullable<DateTime> dOB, String gender, String iDProfe, String iDProfeNo, Byte[] photo, Nullable<DateTime> joinDate, Nullable<DateTime> leaveDate, Nullable<Int32> sponsorsID, String shift, Nullable<Double> salary, Nullable<Double> perDayWorkingHours, Nullable<Double> perHourSalary, Nullable<Boolean> paymentType, String bankName, String branchName, String accountNo, String rTGSNo, String iFSCCode, Nullable<Double> openingBalance, Nullable<Boolean> isDelete, Nullable<Boolean> isActive, Nullable<Int32> createdBY, Nullable<DateTime> createdDate, Nullable<Int32> updatedBy, Nullable<DateTime> updatedDate, List<Int64> tblAttendanceMSTs_AttendanceID, Int64 tblEmployeeTypeMST_EmployeeTypeID, List<Int32> tblSalaryMSTs_SalaryID)
        {
			this.EmployeeID = employeeID;
			this.EmployeeTypeID = employeeTypeID;
			this.EmployeeCode = employeeCode;
			this.JobTitle = jobTitle;
			this.FirstName = firstName;
			this.MiddleName = middleName;
			this.LastName = lastName;
			this.ResidentialAddress = residentialAddress;
			this.PermanentAddress = permanentAddress;
			this.MobileNo = mobileNo;
			this.EmailID = emailID;
			this.DOB = dOB;
			this.Gender = gender;
			this.IDProfe = iDProfe;
			this.IDProfeNo = iDProfeNo;
			this.Photo = photo;
			this.JoinDate = joinDate;
			this.LeaveDate = leaveDate;
			this.SponsorsID = sponsorsID;
			this.Shift = shift;
			this.Salary = salary;
			this.PerDayWorkingHours = perDayWorkingHours;
			this.PerHourSalary = perHourSalary;
			this.PaymentType = paymentType;
			this.BankName = bankName;
			this.BranchName = branchName;
			this.AccountNo = accountNo;
			this.RTGSNo = rTGSNo;
			this.IFSCCode = iFSCCode;
			this.OpeningBalance = openingBalance;
			this.IsDelete = isDelete;
			this.IsActive = isActive;
			this.CreatedBY = createdBY;
			this.CreatedDate = createdDate;
			this.UpdatedBy = updatedBy;
			this.UpdatedDate = updatedDate;
			this.tblAttendanceMSTs_AttendanceID = tblAttendanceMSTs_AttendanceID;
			this.tblEmployeeTypeMST_EmployeeTypeID = tblEmployeeTypeMST_EmployeeTypeID;
			this.tblSalaryMSTs_SalaryID = tblSalaryMSTs_SalaryID;
        }
    }
}
