//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-09 - 14:23:42
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace LoomsManagement.Domain.DTO
{
    [DataContract()]
    public partial class tblLoomProcessWorkDTO
    {
        [DataMember()]
        public Int64 LoomProcessWorkID { get; set; }

        [DataMember()]
        public Nullable<Int64> LoomProcessID { get; set; }

        [DataMember()]
        public Nullable<Int64> EmployeeID { get; set; }

        [DataMember()]
        public Nullable<DateTime> WorkingDate { get; set; }

        [DataMember()]
        public Nullable<TimeSpan> StartTime { get; set; }

        [DataMember()]
        public Nullable<TimeSpan> EndTime { get; set; }

        [DataMember()]
        public String Shift { get; set; }

        [DataMember()]
        public Nullable<Double> MTRStart { get; set; }

        [DataMember()]
        public Nullable<Double> MTREnd { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsDelete { get; set; }

        public tblLoomProcessWorkDTO()
        {
        }

        public tblLoomProcessWorkDTO(Int64 loomProcessWorkID, Nullable<Int64> loomProcessID, Nullable<Int64> employeeID, Nullable<DateTime> workingDate, Nullable<TimeSpan> startTime, Nullable<TimeSpan> endTime, String shift, Nullable<Double> mTRStart, Nullable<Double> mTREnd, Nullable<Boolean> isDelete)
        {
			this.LoomProcessWorkID = loomProcessWorkID;
			this.LoomProcessID = loomProcessID;
			this.EmployeeID = employeeID;
			this.WorkingDate = workingDate;
			this.StartTime = startTime;
			this.EndTime = endTime;
			this.Shift = shift;
			this.MTRStart = mTRStart;
			this.MTREnd = mTREnd;
			this.IsDelete = isDelete;
        }
    }
}
