//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-09 - 14:23:43
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace LoomsManagement.Domain.DTO
{
    [DataContract()]
    public partial class tblMandingProcessDTO
    {
        [DataMember()]
        public Int64 MendingID { get; set; }

        [DataMember()]
        public Nullable<Int32> TakaNo { get; set; }

        [DataMember()]
        public Nullable<Int64> EmployeeID { get; set; }

        [DataMember()]
        public String Grade { get; set; }

        [DataMember()]
        public Nullable<DateTime> StartDateTime { get; set; }

        [DataMember()]
        public Nullable<DateTime> EndDateTime { get; set; }

        [DataMember()]
        public Nullable<Double> TotalMeter { get; set; }

        [DataMember()]
        public Nullable<Int32> TotalNoOfFaults { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsDelete { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsActive { get; set; }

        [DataMember()]
        public Nullable<Int32> CreateBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreationDateTime { get; set; }

        [DataMember()]
        public Nullable<Int32> UpdateBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> UpdationDateTime { get; set; }

        public tblMandingProcessDTO()
        {
        }

        public tblMandingProcessDTO(Int64 mendingID, Nullable<Int32> takaNo, Nullable<Int64> employeeID, String grade, Nullable<DateTime> startDateTime, Nullable<DateTime> endDateTime, Nullable<Double> totalMeter, Nullable<Int32> totalNoOfFaults, Nullable<Boolean> isDelete, Nullable<Boolean> isActive, Nullable<Int32> createBy, Nullable<DateTime> creationDateTime, Nullable<Int32> updateBy, Nullable<DateTime> updationDateTime)
        {
			this.MendingID = mendingID;
			this.TakaNo = takaNo;
			this.EmployeeID = employeeID;
			this.Grade = grade;
			this.StartDateTime = startDateTime;
			this.EndDateTime = endDateTime;
			this.TotalMeter = totalMeter;
			this.TotalNoOfFaults = totalNoOfFaults;
			this.IsDelete = isDelete;
			this.IsActive = isActive;
			this.CreateBy = createBy;
			this.CreationDateTime = creationDateTime;
			this.UpdateBy = updateBy;
			this.UpdationDateTime = updationDateTime;
        }
    }
}
