//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-09 - 14:23:42
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace LoomsManagement.Domain.DTO
{
    [DataContract()]
    public partial class tblMachineMSTDTO
    {
        [DataMember()]
        public Int64 MachineID { get; set; }

        [DataMember()]
        public String MachineName { get; set; }

        [DataMember()]
        public Nullable<Int64> MachineTypeID { get; set; }

        [DataMember()]
        public String AboutMachine { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsDelete { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsActive { get; set; }

        [DataMember()]
        public Nullable<Int32> CreatedBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreatedDateTime { get; set; }

        [DataMember()]
        public Nullable<Int32> UpdatedBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> UpdatedDateTime { get; set; }

        [DataMember()]
        public List<Int64> tblCompanyMachineMSTs_RowId { get; set; }

        public tblMachineMSTDTO()
        {
        }

        public tblMachineMSTDTO(Int64 machineID, String machineName, Nullable<Int64> machineTypeID, String aboutMachine, Nullable<Boolean> isDelete, Nullable<Boolean> isActive, Nullable<Int32> createdBy, Nullable<DateTime> createdDateTime, Nullable<Int32> updatedBy, Nullable<DateTime> updatedDateTime, List<Int64> tblCompanyMachineMSTs_RowId)
        {
			this.MachineID = machineID;
			this.MachineName = machineName;
			this.MachineTypeID = machineTypeID;
			this.AboutMachine = aboutMachine;
			this.IsDelete = isDelete;
			this.IsActive = isActive;
			this.CreatedBy = createdBy;
			this.CreatedDateTime = createdDateTime;
			this.UpdatedBy = updatedBy;
			this.UpdatedDateTime = updatedDateTime;
			this.tblCompanyMachineMSTs_RowId = tblCompanyMachineMSTs_RowId;
        }
    }
}
