//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-09 - 14:23:47
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace LoomsManagement.Domain.DTO
{
    [DataContract()]
    public partial class tblProductQualityMSTDTO
    {
        [DataMember()]
        public Int64 ProductQualityID { get; set; }

        [DataMember()]
        public String ProductQualityName { get; set; }

        [DataMember()]
        public Nullable<Double> WARPDenierAfterTPM { get; set; }

        [DataMember()]
        public Nullable<Int32> WARPNumberOfFilaments { get; set; }

        [DataMember()]
        public Nullable<Int32> WARPYarnQualityID { get; set; }

        [DataMember()]
        public Nullable<Int32> WARPYarnTypeID { get; set; }

        [DataMember()]
        public String WARPDirectionOfTwistS { get; set; }

        [DataMember()]
        public String WARPDirectionOfTwistZ { get; set; }

        [DataMember()]
        public Nullable<Int32> WARPTwistPerMeterS { get; set; }

        [DataMember()]
        public Nullable<Int32> WARPTwistPerMeterZ { get; set; }

        [DataMember()]
        public Nullable<Double> WEFTDenierAfterTPM { get; set; }

        [DataMember()]
        public Nullable<Int32> WEFTNumberOfFilaments1 { get; set; }

        [DataMember()]
        public Nullable<Int32> WEFTYarnQualityID { get; set; }

        [DataMember()]
        public Nullable<Int32> WEFTYarnTypeID { get; set; }

        [DataMember()]
        public String WEFTDirectionOfTwistS { get; set; }

        [DataMember()]
        public String WEFTDirectionOfTwistZ { get; set; }

        [DataMember()]
        public Nullable<Int32> WEFTTwistPerMeterS { get; set; }

        [DataMember()]
        public Nullable<Int32> WEFTTwistPerMeterZ { get; set; }

        [DataMember()]
        public Nullable<Int32> ApproxTotalEndsWithBorder { get; set; }

        [DataMember()]
        public Nullable<Double> ReedOnLoom { get; set; }

        [DataMember()]
        public Nullable<Double> PickOnLoom { get; set; }

        [DataMember()]
        public Nullable<Double> Border { get; set; }

        [DataMember()]
        public String HeatSetting { get; set; }

        [DataMember()]
        public Nullable<Double> WeightOfFabricWARP { get; set; }

        [DataMember()]
        public Nullable<Double> WeightOfFabricWEFT { get; set; }

        [DataMember()]
        public Nullable<Double> TotalWeight { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsDelete { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsActive { get; set; }

        [DataMember()]
        public Nullable<Int32> CreatedBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreatedDateTime { get; set; }

        [DataMember()]
        public Nullable<Int32> UpdatedBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> UpdatedDateTime { get; set; }

        public tblProductQualityMSTDTO()
        {
        }

        public tblProductQualityMSTDTO(Int64 productQualityID, String productQualityName, Nullable<Double> wARPDenierAfterTPM, Nullable<Int32> wARPNumberOfFilaments, Nullable<Int32> wARPYarnQualityID, Nullable<Int32> wARPYarnTypeID, String wARPDirectionOfTwistS, String wARPDirectionOfTwistZ, Nullable<Int32> wARPTwistPerMeterS, Nullable<Int32> wARPTwistPerMeterZ, Nullable<Double> wEFTDenierAfterTPM, Nullable<Int32> wEFTNumberOfFilaments1, Nullable<Int32> wEFTYarnQualityID, Nullable<Int32> wEFTYarnTypeID, String wEFTDirectionOfTwistS, String wEFTDirectionOfTwistZ, Nullable<Int32> wEFTTwistPerMeterS, Nullable<Int32> wEFTTwistPerMeterZ, Nullable<Int32> approxTotalEndsWithBorder, Nullable<Double> reedOnLoom, Nullable<Double> pickOnLoom, Nullable<Double> border, String heatSetting, Nullable<Double> weightOfFabricWARP, Nullable<Double> weightOfFabricWEFT, Nullable<Double> totalWeight, Nullable<Boolean> isDelete, Nullable<Boolean> isActive, Nullable<Int32> createdBy, Nullable<DateTime> createdDateTime, Nullable<Int32> updatedBy, Nullable<DateTime> updatedDateTime)
        {
			this.ProductQualityID = productQualityID;
			this.ProductQualityName = productQualityName;
			this.WARPDenierAfterTPM = wARPDenierAfterTPM;
			this.WARPNumberOfFilaments = wARPNumberOfFilaments;
			this.WARPYarnQualityID = wARPYarnQualityID;
			this.WARPYarnTypeID = wARPYarnTypeID;
			this.WARPDirectionOfTwistS = wARPDirectionOfTwistS;
			this.WARPDirectionOfTwistZ = wARPDirectionOfTwistZ;
			this.WARPTwistPerMeterS = wARPTwistPerMeterS;
			this.WARPTwistPerMeterZ = wARPTwistPerMeterZ;
			this.WEFTDenierAfterTPM = wEFTDenierAfterTPM;
			this.WEFTNumberOfFilaments1 = wEFTNumberOfFilaments1;
			this.WEFTYarnQualityID = wEFTYarnQualityID;
			this.WEFTYarnTypeID = wEFTYarnTypeID;
			this.WEFTDirectionOfTwistS = wEFTDirectionOfTwistS;
			this.WEFTDirectionOfTwistZ = wEFTDirectionOfTwistZ;
			this.WEFTTwistPerMeterS = wEFTTwistPerMeterS;
			this.WEFTTwistPerMeterZ = wEFTTwistPerMeterZ;
			this.ApproxTotalEndsWithBorder = approxTotalEndsWithBorder;
			this.ReedOnLoom = reedOnLoom;
			this.PickOnLoom = pickOnLoom;
			this.Border = border;
			this.HeatSetting = heatSetting;
			this.WeightOfFabricWARP = weightOfFabricWARP;
			this.WeightOfFabricWEFT = weightOfFabricWEFT;
			this.TotalWeight = totalWeight;
			this.IsDelete = isDelete;
			this.IsActive = isActive;
			this.CreatedBy = createdBy;
			this.CreatedDateTime = createdDateTime;
			this.UpdatedBy = updatedBy;
			this.UpdatedDateTime = updatedDateTime;
        }
    }
}
