//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-15 - 10:24:05
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace LoomsManagement.Domain.DTO
{
    [DataContract()]
    public partial class tblProfeListMstDTO
    {
        [DataMember()]
        public Int32 ProfeID { get; set; }

        [DataMember()]
        public String Name { get; set; }

        public tblProfeListMstDTO()
        {
        }

        public tblProfeListMstDTO(Int32 profeID, String name)
        {
			this.ProfeID = profeID;
			this.Name = name;
        }
    }
}
