//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-15 - 10:24:05
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace LoomsManagement.Domain.DTO
{
    [DataContract()]
    public partial class tblProfeListMstDTO
    {
        [DataMember()]
        public Int32 ProfeID { get; set; }

        [DataMember()]
        public String Name { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsDelete { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsActive { get; set; }

        [DataMember()]
        public Nullable<Int32> CreatedBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreatedDateTime { get; set; }

        [DataMember()]
        public Nullable<Int32> UpdateBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> UpdateDateTime { get; set; }


        public tblProfeListMstDTO()
        {
        }

        public tblProfeListMstDTO(Int32 profeID, String name, Nullable<Boolean> isDelete, Nullable<Boolean> isActive, Nullable<Int32> createBy, Nullable<DateTime> creationDateTime, Nullable<Int32> updateBy, Nullable<DateTime> updationDateTime)
        {
			this.ProfeID = profeID;
			this.Name = name;
            this.IsDelete = isDelete;
            this.IsActive = isActive;
            this.CreatedBy = createBy;
            this.CreatedDateTime = creationDateTime;
            this.UpdateBy=updateBy;
            this.UpdateDateTime = updationDateTime;
        }
    }
}
