//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-09 - 14:23:45
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace LoomsManagement.Domain.DTO
{
    [DataContract()]
    public partial class tblPartysMSTDTO
    {
        [DataMember()]
        public Int64 PartyID { get; set; }

        [DataMember()]
        public Nullable<Int32> CompanyCode { get; set; }

        [DataMember()]
        public String PartyName { get; set; }

        [DataMember()]
        public String ContactPersonName { get; set; }

        [DataMember()]
        public String OfficeAddress { get; set; }

        [DataMember()]
        public String ShippingAddress { get; set; }

        [DataMember()]
        public String City { get; set; }

        [DataMember()]
        public String State { get; set; }

        [DataMember()]
        public String MobileNo { get; set; }

        [DataMember()]
        public String PhoneNo { get; set; }

        [DataMember()]
        public String SMSNo { get; set; }

        [DataMember()]
        public String ReferencePersonName { get; set; }

        [DataMember()]
        public String ReferencePersonMobileNo { get; set; }

        [DataMember()]
        public String EmailID { get; set; }

        [DataMember()]
        public String ExtraDetails { get; set; }

        [DataMember()]
        public String TINNo { get; set; }

        [DataMember()]
        public Nullable<DateTime> TINDate { get; set; }

        [DataMember()]
        public String PANNO { get; set; }

        [DataMember()]
        public String CSTTINNo { get; set; }

        [DataMember()]
        public Nullable<DateTime> CSTDate { get; set; }

        [DataMember()]
        public String ECCNo { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsDelete { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsActive { get; set; }

        [DataMember()]
        public Nullable<Int32> CreateBye { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreationDateTime { get; set; }

        [DataMember()]
        public Nullable<Int32> UpdateBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> UpdationDateTIme { get; set; }

        public tblPartysMSTDTO()
        {
        }

        public tblPartysMSTDTO(Int64 partyID, Nullable<Int32> companyCode, String partyName, String contactPersonName, String officeAddress, String shippingAddress, String city, String state, String mobileNo, String phoneNo, String sMSNo, String referencePersonName, String referencePersonMobileNo, String emailID, String extraDetails, String tINNo, Nullable<DateTime> tINDate, String pANNO, String cSTTINNo, Nullable<DateTime> cSTDate, String eCCNo, Nullable<Boolean> isDelete, Nullable<Boolean> isActive, Nullable<Int32> createBye, Nullable<DateTime> creationDateTime, Nullable<Int32> updateBy, Nullable<DateTime> updationDateTIme)
        {
			this.PartyID = partyID;
			this.CompanyCode = companyCode;
			this.PartyName = partyName;
			this.ContactPersonName = contactPersonName;
			this.OfficeAddress = officeAddress;
			this.ShippingAddress = shippingAddress;
			this.City = city;
			this.State = state;
			this.MobileNo = mobileNo;
			this.PhoneNo = phoneNo;
			this.SMSNo = sMSNo;
			this.ReferencePersonName = referencePersonName;
			this.ReferencePersonMobileNo = referencePersonMobileNo;
			this.EmailID = emailID;
			this.ExtraDetails = extraDetails;
			this.TINNo = tINNo;
			this.TINDate = tINDate;
			this.PANNO = pANNO;
			this.CSTTINNo = cSTTINNo;
			this.CSTDate = cSTDate;
			this.ECCNo = eCCNo;
			this.IsDelete = isDelete;
			this.IsActive = isActive;
			this.CreateBye = createBye;
			this.CreationDateTime = creationDateTime;
			this.UpdateBy = updateBy;
			this.UpdationDateTIme = updationDateTIme;
        }
    }
}
