//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-09 - 14:23:48
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace LoomsManagement.Domain.DTO
{
    [DataContract()]
    public partial class tblSalaryMSTDTO
    {
        [DataMember()]
        public Int32 SalaryID { get; set; }

        [DataMember()]
        public Nullable<Int64> EmployeeID { get; set; }

        [DataMember()]
        public Nullable<DateTime> Date { get; set; }

        [DataMember()]
        public Nullable<DateTime> StartDate { get; set; }

        [DataMember()]
        public Nullable<DateTime> EndDate { get; set; }

        [DataMember()]
        public Nullable<Double> WorkedHours { get; set; }

        [DataMember()]
        public Nullable<Double> TotalPenalty { get; set; }

        [DataMember()]
        public Nullable<Double> Bonus { get; set; }

        [DataMember()]
        public Nullable<Double> WithdrownAmount { get; set; }

        [DataMember()]
        public Nullable<Int64> WithdrownID { get; set; }

        [DataMember()]
        public Nullable<Double> NetSalary { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsDelete { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsActive { get; set; }

        [DataMember()]
        public Nullable<Int32> CreateBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreationDateTime { get; set; }

        [DataMember()]
        public Nullable<Int32> UpdateBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> UpdationDateTime { get; set; }

        [DataMember()]
        public Int64 tblEmployee_EmployeeID { get; set; }

        public tblSalaryMSTDTO()
        {
        }

        public tblSalaryMSTDTO(Int32 salaryID, Nullable<Int64> employeeID, Nullable<DateTime> date, Nullable<DateTime> startDate, Nullable<DateTime> endDate, Nullable<Double> workedHours, Nullable<Double> totalPenalty, Nullable<Double> bonus, Nullable<Double> withdrownAmount, Nullable<Int64> withdrownID, Nullable<Double> netSalary, Nullable<Boolean> isDelete, Nullable<Boolean> isActive, Nullable<Int32> createBy, Nullable<DateTime> creationDateTime, Nullable<Int32> updateBy, Nullable<DateTime> updationDateTime, Int64 tblEmployee_EmployeeID)
        {
			this.SalaryID = salaryID;
			this.EmployeeID = employeeID;
			this.Date = date;
			this.StartDate = startDate;
			this.EndDate = endDate;
			this.WorkedHours = workedHours;
			this.TotalPenalty = totalPenalty;
			this.Bonus = bonus;
			this.WithdrownAmount = withdrownAmount;
			this.WithdrownID = withdrownID;
			this.NetSalary = netSalary;
			this.IsDelete = isDelete;
			this.IsActive = isActive;
			this.CreateBy = createBy;
			this.CreationDateTime = creationDateTime;
			this.UpdateBy = updateBy;
			this.UpdationDateTime = updationDateTime;
			this.tblEmployee_EmployeeID = tblEmployee_EmployeeID;
        }
    }
}
