//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-09 - 14:23:49
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace LoomsManagement.Domain.DTO
{
    [DataContract()]
    public partial class tblTFOProcessDTO
    {
        [DataMember()]
        public Int64 TFORoleProcessId { get; set; }

        [DataMember()]
        public Nullable<Int32> WindingProcessId { get; set; }

        [DataMember()]
        public Nullable<Int32> PurchaseItemID { get; set; }

        [DataMember()]
        public Nullable<Int32> MachineId { get; set; }

        [DataMember()]
        public Nullable<Int32> EmployeeId { get; set; }

        [DataMember()]
        public String Shift { get; set; }

        [DataMember()]
        public Nullable<DateTime> StartDateTime { get; set; }

        [DataMember()]
        public Nullable<Int32> IssueNoOfCopes { get; set; }

        [DataMember()]
        public Nullable<Double> IssueWights { get; set; }

        [DataMember()]
        public Nullable<Double> NoofTFORole { get; set; }

        [DataMember()]
        public Nullable<Int32> ProducttionNoOfTFORoles { get; set; }

        [DataMember()]
        public Nullable<Double> ProducttionWights { get; set; }

        [DataMember()]
        public String QualityName { get; set; }

        [DataMember()]
        public Nullable<DateTime> EndDateTime { get; set; }

        [DataMember()]
        public Nullable<Int32> YarnQualityId { get; set; }

        [DataMember()]
        public Nullable<Int32> YarnTypeId { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsDelete { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsActive { get; set; }

        [DataMember()]
        public Nullable<Int32> UpdateBy { get; set; }

        [DataMember()]
        public Nullable<Int32> CreateBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> UpdationDateTime { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreationDateTIme { get; set; }

        [DataMember()]
        public List<Int64> tblBemProcessDetails_BemProcessDetailsID { get; set; }

        [DataMember()]
        public List<Int64> tblBolierProcessDetails_BoilerProcessDetailsID { get; set; }

        [DataMember()]
        public Int32 tblWindingWork_WindingProcessId { get; set; }

        public tblTFOProcessDTO()
        {
        }

        public tblTFOProcessDTO(Int64 tFORoleProcessId, Nullable<Int32> windingProcessId, Nullable<Int32> purchaseItemID, Nullable<Int32> machineId, Nullable<Int32> employeeId, String shift, Nullable<DateTime> startDateTime, Nullable<Int32> issueNoOfCopes, Nullable<Double> issueWights, Nullable<Double> noofTFORole, Nullable<Int32> producttionNoOfTFORoles, Nullable<Double> producttionWights, String qualityName, Nullable<DateTime> endDateTime, Nullable<Int32> yarnQualityId, Nullable<Int32> yarnTypeId, Nullable<Boolean> isDelete, Nullable<Boolean> isActive, Nullable<Int32> updateBy, Nullable<Int32> createBy, Nullable<DateTime> updationDateTime, Nullable<DateTime> creationDateTIme, List<Int64> tblBemProcessDetails_BemProcessDetailsID, List<Int64> tblBolierProcessDetails_BoilerProcessDetailsID, Int32 tblWindingWork_WindingProcessId)
        {
			this.TFORoleProcessId = tFORoleProcessId;
			this.WindingProcessId = windingProcessId;
			this.PurchaseItemID = purchaseItemID;
			this.MachineId = machineId;
			this.EmployeeId = employeeId;
			this.Shift = shift;
			this.StartDateTime = startDateTime;
			this.IssueNoOfCopes = issueNoOfCopes;
			this.IssueWights = issueWights;
			this.NoofTFORole = noofTFORole;
			this.ProducttionNoOfTFORoles = producttionNoOfTFORoles;
			this.ProducttionWights = producttionWights;
			this.QualityName = qualityName;
			this.EndDateTime = endDateTime;
			this.YarnQualityId = yarnQualityId;
			this.YarnTypeId = yarnTypeId;
			this.IsDelete = isDelete;
			this.IsActive = isActive;
			this.UpdateBy = updateBy;
			this.CreateBy = createBy;
			this.UpdationDateTime = updationDateTime;
			this.CreationDateTIme = creationDateTIme;
			this.tblBemProcessDetails_BemProcessDetailsID = tblBemProcessDetails_BemProcessDetailsID;
			this.tblBolierProcessDetails_BoilerProcessDetailsID = tblBolierProcessDetails_BoilerProcessDetailsID;
			this.tblWindingWork_WindingProcessId = tblWindingWork_WindingProcessId;
        }
    }
}
