//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-09 - 14:23:51
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace LoomsManagement.Domain.DTO
{
    [DataContract()]
    public partial class tblWithdrownMSTDTO
    {
        [DataMember()]
        public Int64 WithdrownID { get; set; }

        [DataMember()]
        public Nullable<Int64> EmployeeID { get; set; }

        [DataMember()]
        public String Remarks { get; set; }

        [DataMember()]
        public Nullable<Double> WithdrownAmount { get; set; }

        [DataMember()]
        public Nullable<DateTime> WithdrownDate { get; set; }

        [DataMember()]
        public Nullable<DateTime> ReturnDate { get; set; }

        [DataMember()]
        public Nullable<Boolean> ISStatus { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsActive { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsDelete { get; set; }

        [DataMember()]
        public Nullable<Int32> CreateBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreationDateTime { get; set; }

        [DataMember()]
        public Nullable<Int32> UpdateBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> UpdationDateTime { get; set; }

        public tblWithdrownMSTDTO()
        {
        }

        public tblWithdrownMSTDTO(Int64 withdrownID, Nullable<Int64> employeeID, String remarks, Nullable<Double> withdrownAmount, Nullable<DateTime> withdrownDate, Nullable<DateTime> returnDate, Nullable<Boolean> iSStatus, Nullable<Boolean> isActive, Nullable<Boolean> isDelete, Nullable<Int32> createBy, Nullable<DateTime> creationDateTime, Nullable<Int32> updateBy, Nullable<DateTime> updationDateTime)
        {
			this.WithdrownID = withdrownID;
			this.EmployeeID = employeeID;
			this.Remarks = remarks;
			this.WithdrownAmount = withdrownAmount;
			this.WithdrownDate = withdrownDate;
			this.ReturnDate = returnDate;
			this.ISStatus = iSStatus;
			this.IsActive = isActive;
			this.IsDelete = isDelete;
			this.CreateBy = createBy;
			this.CreationDateTime = creationDateTime;
			this.UpdateBy = updateBy;
			this.UpdationDateTime = updationDateTime;
        }
    }
}
