//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-09 - 14:23:50
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace LoomsManagement.Domain.DTO
{
    [DataContract()]
    public partial class tblWindingWorkDTO
    {
        [DataMember()]
        public Int32 WindingProcessId { get; set; }

        [DataMember()]
        public Nullable<Int32> MachineId { get; set; }

        [DataMember()]
        public Nullable<Int32> EmployeeId { get; set; }

        [DataMember()]
        public Nullable<Int64> PuchaseItemId { get; set; }

        [DataMember()]
        public String Shift { get; set; }

        [DataMember()]
        public Nullable<DateTime> StartDateTime { get; set; }

        [DataMember()]
        public Nullable<Double> TotalIssueWeight { get; set; }

        [DataMember()]
        public Nullable<Double> WastedWeight { get; set; }

        [DataMember()]
        public Nullable<Double> ProductionWeight { get; set; }

        [DataMember()]
        public Nullable<Int32> NoOfCopes { get; set; }

        [DataMember()]
        public Nullable<DateTime> EndDateTime { get; set; }

        [DataMember()]
        public Nullable<Int32> YarnQualityId { get; set; }

        [DataMember()]
        public Nullable<Int32> YarnTypeId { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsDelete { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsActive { get; set; }

        [DataMember()]
        public Nullable<Int32> UpdateBy { get; set; }

        [DataMember()]
        public Nullable<Int32> CreateBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> UpdationDateTime { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreationDateTIme { get; set; }

        [DataMember()]
        public List<Int64> tblTFOProcesses_TFORoleProcessId { get; set; }

        [DataMember()]
        public Int64 tblYarnPurchaseItem_PurchaseItemID { get; set; }

        public tblWindingWorkDTO()
        {
        }

        public tblWindingWorkDTO(Int32 windingProcessId, Nullable<Int32> machineId, Nullable<Int32> employeeId, Nullable<Int64> puchaseItemId, String shift, Nullable<DateTime> startDateTime, Nullable<Double> totalIssueWeight, Nullable<Double> wastedWeight, Nullable<Double> productionWeight, Nullable<Int32> noOfCopes, Nullable<DateTime> endDateTime, Nullable<Int32> yarnQualityId, Nullable<Int32> yarnTypeId, Nullable<Boolean> isDelete, Nullable<Boolean> isActive, Nullable<Int32> updateBy, Nullable<Int32> createBy, Nullable<DateTime> updationDateTime, Nullable<DateTime> creationDateTIme, List<Int64> tblTFOProcesses_TFORoleProcessId, Int64 tblYarnPurchaseItem_PurchaseItemID)
        {
			this.WindingProcessId = windingProcessId;
			this.MachineId = machineId;
			this.EmployeeId = employeeId;
			this.PuchaseItemId = puchaseItemId;
			this.Shift = shift;
			this.StartDateTime = startDateTime;
			this.TotalIssueWeight = totalIssueWeight;
			this.WastedWeight = wastedWeight;
			this.ProductionWeight = productionWeight;
			this.NoOfCopes = noOfCopes;
			this.EndDateTime = endDateTime;
			this.YarnQualityId = yarnQualityId;
			this.YarnTypeId = yarnTypeId;
			this.IsDelete = isDelete;
			this.IsActive = isActive;
			this.UpdateBy = updateBy;
			this.CreateBy = createBy;
			this.UpdationDateTime = updationDateTime;
			this.CreationDateTIme = creationDateTIme;
			this.tblTFOProcesses_TFORoleProcessId = tblTFOProcesses_TFORoleProcessId;
			this.tblYarnPurchaseItem_PurchaseItemID = tblYarnPurchaseItem_PurchaseItemID;
        }
    }
}
