//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-09 - 14:23:54
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace LoomsManagement.Domain.DTO
{
    [DataContract()]
    public partial class tblYarnPurchaseItemDTO
    {
        [DataMember()]
        public Int64 PurchaseItemID { get; set; }

        [DataMember()]
        public Nullable<Int64> PurchaseID { get; set; }

        [DataMember()]
        public Nullable<Int64> YarnID { get; set; }

        [DataMember()]
        public Nullable<Int64> YarnPackageTypeID { get; set; }

        [DataMember()]
        public Nullable<DateTime> PurchaseDate { get; set; }

        [DataMember()]
        public String BoxNo { get; set; }

        [DataMember()]
        public Nullable<Double> GrossWeight { get; set; }

        [DataMember()]
        public Nullable<Double> TareWeight { get; set; }

        [DataMember()]
        public Nullable<Double> NetWeight { get; set; }

        [DataMember()]
        public Nullable<Double> Cheese { get; set; }

        [DataMember()]
        public Nullable<Int64> EmployeeID { get; set; }

        [DataMember()]
        public Nullable<Int64> YarnQualityID { get; set; }

        [DataMember()]
        public Nullable<Int64> YarnTypeID { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsDelete { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsActive { get; set; }

        [DataMember()]
        public Nullable<Int32> UpdateBy { get; set; }

        [DataMember()]
        public Nullable<Int32> CreateBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> UpdationDateTime { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreationDateTIme { get; set; }

        [DataMember()]
        public List<Int32> tblWindingWorks_WindingProcessId { get; set; }

        [DataMember()]
        public Int64 tblYarnPackageType_YarnPackageTypeID { get; set; }

        [DataMember()]
        public Int64 tblYarnPurchase_PurchaseID { get; set; }

        [DataMember()]
        public Int64 tblYarnQualityMST_YarnQualityID { get; set; }

        [DataMember()]
        public Int64 tblYarnQualityMST1_YarnQualityID { get; set; }

        [DataMember()]
        public Int64 tblYarnTypeMST_YarnTypeID { get; set; }

        public tblYarnPurchaseItemDTO()
        {
        }

        public tblYarnPurchaseItemDTO(Int64 purchaseItemID, Nullable<Int64> purchaseID, Nullable<Int64> yarnID, Nullable<Int64> yarnPackageTypeID, Nullable<DateTime> purchaseDate, String boxNo, Nullable<Double> grossWeight, Nullable<Double> tareWeight, Nullable<Double> netWeight, Nullable<Double> cheese, Nullable<Int64> employeeID, Nullable<Int64> yarnQualityID, Nullable<Int64> yarnTypeID, Nullable<Boolean> isDelete, Nullable<Boolean> isActive, Nullable<Int32> updateBy, Nullable<Int32> createBy, Nullable<DateTime> updationDateTime, Nullable<DateTime> creationDateTIme, List<Int32> tblWindingWorks_WindingProcessId, Int64 tblYarnPackageType_YarnPackageTypeID, Int64 tblYarnPurchase_PurchaseID, Int64 tblYarnQualityMST_YarnQualityID, Int64 tblYarnQualityMST1_YarnQualityID, Int64 tblYarnTypeMST_YarnTypeID)
        {
			this.PurchaseItemID = purchaseItemID;
			this.PurchaseID = purchaseID;
			this.YarnID = yarnID;
			this.YarnPackageTypeID = yarnPackageTypeID;
			this.PurchaseDate = purchaseDate;
			this.BoxNo = boxNo;
			this.GrossWeight = grossWeight;
			this.TareWeight = tareWeight;
			this.NetWeight = netWeight;
			this.Cheese = cheese;
			this.EmployeeID = employeeID;
			this.YarnQualityID = yarnQualityID;
			this.YarnTypeID = yarnTypeID;
			this.IsDelete = isDelete;
			this.IsActive = isActive;
			this.UpdateBy = updateBy;
			this.CreateBy = createBy;
			this.UpdationDateTime = updationDateTime;
			this.CreationDateTIme = creationDateTIme;
			this.tblWindingWorks_WindingProcessId = tblWindingWorks_WindingProcessId;
			this.tblYarnPackageType_YarnPackageTypeID = tblYarnPackageType_YarnPackageTypeID;
			this.tblYarnPurchase_PurchaseID = tblYarnPurchase_PurchaseID;
			this.tblYarnQualityMST_YarnQualityID = tblYarnQualityMST_YarnQualityID;
			this.tblYarnQualityMST1_YarnQualityID = tblYarnQualityMST1_YarnQualityID;
			this.tblYarnTypeMST_YarnTypeID = tblYarnTypeMST_YarnTypeID;
        }
    }
}
