//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-09 - 14:23:55
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace LoomsManagement.Domain.DTO
{
    [DataContract()]
    public partial class tblYarnQualityMSTDTO
    {
        [DataMember()]
        public Int64 YarnQualityID { get; set; }

        [DataMember()]
        public String YarnQualityName { get; set; }

        [DataMember()]
        public String Description { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsDelete { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsActive { get; set; }

        [DataMember()]
        public Nullable<Int32> CreateBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreationDateTime { get; set; }

        [DataMember()]
        public Nullable<Int32> UpdateBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> UpdationDateTime { get; set; }

        [DataMember()]
        public List<Int64> tblYarnPurchaseItems_PurchaseItemID { get; set; }

        [DataMember()]
        public List<Int64> tblYarnPurchaseItems1_PurchaseItemID { get; set; }

        [DataMember()]
        public List<Int64> tblYarnTypeMSTs_YarnTypeID { get; set; }

        public tblYarnQualityMSTDTO()
        {
        }

        public tblYarnQualityMSTDTO(Int64 yarnQualityID, String yarnQualityName, String description, Nullable<Boolean> isDelete, Nullable<Boolean> isActive, Nullable<Int32> createBy, Nullable<DateTime> creationDateTime, Nullable<Int32> updateBy, Nullable<DateTime> updationDateTime, List<Int64> tblYarnPurchaseItems_PurchaseItemID, List<Int64> tblYarnPurchaseItems1_PurchaseItemID, List<Int64> tblYarnTypeMSTs_YarnTypeID)
        {
			this.YarnQualityID = yarnQualityID;
			this.YarnQualityName = yarnQualityName;
			this.Description = description;
			this.IsDelete = isDelete;
			this.IsActive = isActive;
			this.CreateBy = createBy;
			this.CreationDateTime = creationDateTime;
			this.UpdateBy = updateBy;
			this.UpdationDateTime = updationDateTime;
			this.tblYarnPurchaseItems_PurchaseItemID = tblYarnPurchaseItems_PurchaseItemID;
			this.tblYarnPurchaseItems1_PurchaseItemID = tblYarnPurchaseItems1_PurchaseItemID;
			this.tblYarnTypeMSTs_YarnTypeID = tblYarnTypeMSTs_YarnTypeID;
        }
    }
}
