//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-09 - 14:23:55
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace LoomsManagement.Domain.DTO
{
    [DataContract()]
    public partial class tblYarnTypeMSTDTO
    {
        [DataMember()]
        public Int64 YarnTypeID { get; set; }

        [DataMember()]
        public String YarnTypeName { get; set; }

        [DataMember()]
        public Nullable<Int64> YarnQualityID { get; set; }

        [DataMember()]
        public String Denier { get; set; }

        [DataMember()]
        public Nullable<Int32> NumberOfFilaments { get; set; }

        [DataMember()]
        public String Description { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsActive { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsDelete { get; set; }

        [DataMember()]
        public Nullable<Int32> UpdateBy { get; set; }

        [DataMember()]
        public Nullable<Int32> CreateBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> UpdationDateTime { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreationDateTIme { get; set; }

        [DataMember()]
        public List<Int64> tblYarnPurchaseItems_PurchaseItemID { get; set; }

        [DataMember()]
        public Int64 tblYarnQualityMST_YarnQualityID { get; set; }

        public tblYarnTypeMSTDTO()
        {
        }

        public tblYarnTypeMSTDTO(Int64 yarnTypeID, String yarnTypeName, Nullable<Int64> yarnQualityID, String denier, Nullable<Int32> numberOfFilaments, String description, Nullable<Boolean> isActive, Nullable<Boolean> isDelete, Nullable<Int32> updateBy, Nullable<Int32> createBy, Nullable<DateTime> updationDateTime, Nullable<DateTime> creationDateTIme, List<Int64> tblYarnPurchaseItems_PurchaseItemID, Int64 tblYarnQualityMST_YarnQualityID)
        {
			this.YarnTypeID = yarnTypeID;
			this.YarnTypeName = yarnTypeName;
			this.YarnQualityID = yarnQualityID;
			this.Denier = denier;
			this.NumberOfFilaments = numberOfFilaments;
			this.Description = description;
			this.IsActive = isActive;
			this.IsDelete = isDelete;
			this.UpdateBy = updateBy;
			this.CreateBy = createBy;
			this.UpdationDateTime = updationDateTime;
			this.CreationDateTIme = creationDateTIme;
			this.tblYarnPurchaseItems_PurchaseItemID = tblYarnPurchaseItems_PurchaseItemID;
			this.tblYarnQualityMST_YarnQualityID = tblYarnQualityMST_YarnQualityID;
        }
    }
}
