//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-09 - 14:23:53
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace LoomsManagement.Domain.DTO
{
    [DataContract()]
    public partial class tblYarnPurchaseDTO
    {
        [DataMember()]
        public Int64 PurchaseID { get; set; }

        [DataMember()]
        public Nullable<Int32> SRNo { get; set; }

        [DataMember()]
        public Nullable<Int64> CompanyID { get; set; }

        [DataMember()]
        public Int64 PartyID { get; set; }

        [DataMember()]
        public Nullable<Int64> BrokerID { get; set; }

        [DataMember()]
        public Nullable<Int64> YearID { get; set; }

        [DataMember()]
        public Nullable<DateTime> PurchaseDate { get; set; }

        [DataMember()]
        public String ChallanNo { get; set; }

        [DataMember()]
        public String LRNo { get; set; }

        [DataMember()]
        public String RecieveAt { get; set; }

        [DataMember()]
        public String Grade { get; set; }

        [DataMember()]
        public Nullable<Int32> EmployeeId { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsDelete { get; set; }

        [DataMember()]
        public String IsDelete_bit_Checked { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsActive { get; set; }

        [DataMember()]
        public Nullable<Int32> CreatedBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreatedDateTime { get; set; }

        [DataMember()]
        public Nullable<Int32> UpdatedBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> UpDatedDateTime { get; set; }

        [DataMember()]
        public List<Int64> tblYarnPurchaseItems_PurchaseItemID { get; set; }

        public tblYarnPurchaseDTO()
        {
        }

        public tblYarnPurchaseDTO(Int64 purchaseID, Nullable<Int32> sRNo, Nullable<Int64> companyID, Int64 partyID, Nullable<Int64> brokerID, Nullable<Int64> yearID, Nullable<DateTime> purchaseDate, String challanNo, String lRNo, String recieveAt, String grade, Nullable<Int32> employeeId, Nullable<Boolean> isDelete, String isDelete_bit_Checked, Nullable<Boolean> isActive, Nullable<Int32> createdBy, Nullable<DateTime> createdDateTime, Nullable<Int32> updatedBy, Nullable<DateTime> upDatedDateTime, List<Int64> tblYarnPurchaseItems_PurchaseItemID)
        {
			this.PurchaseID = purchaseID;
			this.SRNo = sRNo;
			this.CompanyID = companyID;
			this.PartyID = partyID;
			this.BrokerID = brokerID;
			this.YearID = yearID;
			this.PurchaseDate = purchaseDate;
			this.ChallanNo = challanNo;
			this.LRNo = lRNo;
			this.RecieveAt = recieveAt;
			this.Grade = grade;
			this.EmployeeId = employeeId;
			this.IsDelete = isDelete;
			this.IsDelete_bit_Checked = isDelete_bit_Checked;
			this.IsActive = isActive;
			this.CreatedBy = createdBy;
			this.CreatedDateTime = createdDateTime;
			this.UpdatedBy = updatedBy;
			this.UpDatedDateTime = upDatedDateTime;
			this.tblYarnPurchaseItems_PurchaseItemID = tblYarnPurchaseItems_PurchaseItemID;
        }
    }
}
