//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-09 - 14:23:56
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace LoomsManagement.Domain.DTO
{
    [DataContract()]
    public partial class WithdrownReturnMSTDTO
    {
        [DataMember()]
        public Int64 WithdrownReturnID { get; set; }

        [DataMember()]
        public Nullable<DateTime> Date { get; set; }

        [DataMember()]
        public Nullable<Int64> EmployeeID { get; set; }

        [DataMember()]
        public Nullable<Int32> ReturnType { get; set; }

        [DataMember()]
        public Nullable<Int64> SalaryID { get; set; }

        [DataMember()]
        public Nullable<Double> Amount { get; set; }

        [DataMember()]
        public String Remark { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsDelete { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsActive { get; set; }

        [DataMember()]
        public Nullable<Int32> CreateBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreationDateTime { get; set; }

        [DataMember()]
        public Nullable<Int32> UpdateBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> UpdationDateTime { get; set; }

        public WithdrownReturnMSTDTO()
        {
        }

        public WithdrownReturnMSTDTO(Int64 withdrownReturnID, Nullable<DateTime> date, Nullable<Int64> employeeID, Nullable<Int32> returnType, Nullable<Int64> salaryID, Nullable<Double> amount, String remark, Nullable<Boolean> isDelete, Nullable<Boolean> isActive, Nullable<Int32> createBy, Nullable<DateTime> creationDateTime, Nullable<Int32> updateBy, Nullable<DateTime> updationDateTime)
        {
			this.WithdrownReturnID = withdrownReturnID;
			this.Date = date;
			this.EmployeeID = employeeID;
			this.ReturnType = returnType;
			this.SalaryID = salaryID;
			this.Amount = amount;
			this.Remark = remark;
			this.IsDelete = isDelete;
			this.IsActive = isActive;
			this.CreateBy = createBy;
			this.CreationDateTime = creationDateTime;
			this.UpdateBy = updateBy;
			this.UpdationDateTime = updationDateTime;
        }
    }
}
