//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-08 - 11:39:06
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using LoomsManagement.Domain.DTO;
using LoomsManagement.Database.ORM;

namespace LoomsManagement.DAL.Assemblers
{

    /// <summary>
    /// Assembler for <see cref="tblBankMST"/> and <see cref="tblBankMSTDTO"/>.
    /// </summary>
    public static partial class tblBankMSTAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tblBankMSTDTO"/> converted from <see cref="tblBankMST"/>.</param>
        static partial void OnDTO(this tblBankMST entity, tblBankMSTDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tblBankMST"/> converted from <see cref="tblBankMSTDTO"/>.</param>
        static partial void OnEntity(this tblBankMSTDTO dto, tblBankMST entity);

        /// <summary>
        /// Converts this instance of <see cref="tblBankMSTDTO"/> to an instance of <see cref="tblBankMST"/>.
        /// </summary>
        /// <param name="dto"><see cref="tblBankMSTDTO"/> to convert.</param>
        public static tblBankMST ToEntity(this tblBankMSTDTO dto)
        {
            if (dto == null) return null;

            var entity = new tblBankMST();

            entity.BankID = dto.BankID;
            entity.BankName = dto.BankName;
            entity.IsActive = dto.IsActive;
            entity.CreateBy = dto.CreateBy;
            entity.CreationDateTime = dto.CreationDateTime;
            entity.UpdateBy = dto.UpdateBy;
            entity.UpdationDateTime = dto.UpdationDateTime;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tblBankMST"/> to an instance of <see cref="tblBankMSTDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tblBankMST"/> to convert.</param>
        public static tblBankMSTDTO ToDTO(this tblBankMST entity)
        {
            if (entity == null) return null;

            var dto = new tblBankMSTDTO();

            dto.BankID = entity.BankID;
            dto.BankName = entity.BankName;
            dto.IsActive = entity.IsActive;
            dto.CreateBy = entity.CreateBy;
            dto.CreationDateTime = entity.CreationDateTime;
            dto.UpdateBy = entity.UpdateBy;
            dto.UpdationDateTime = entity.UpdationDateTime;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tblBankMSTDTO"/> to an instance of <see cref="tblBankMST"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tblBankMST> ToEntities(this IEnumerable<tblBankMSTDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tblBankMST"/> to an instance of <see cref="tblBankMSTDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tblBankMSTDTO> ToDTOs(this IEnumerable<tblBankMST> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
