//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-08 - 11:39:07
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using LoomsManagement.Domain.DTO;
using LoomsManagement.Database.ORM;

namespace LoomsManagement.DAL.Assemblers
{

    /// <summary>
    /// Assembler for <see cref="tblCompany"/> and <see cref="tblCompanyDTO"/>.
    /// </summary>
    public static partial class tblCompanyAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tblCompanyDTO"/> converted from <see cref="tblCompany"/>.</param>
        static partial void OnDTO(this tblCompany entity, tblCompanyDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tblCompany"/> converted from <see cref="tblCompanyDTO"/>.</param>
        static partial void OnEntity(this tblCompanyDTO dto, tblCompany entity);

        /// <summary>
        /// Converts this instance of <see cref="tblCompanyDTO"/> to an instance of <see cref="tblCompany"/>.
        /// </summary>
        /// <param name="dto"><see cref="tblCompanyDTO"/> to convert.</param>
        public static tblCompany ToEntity(this tblCompanyDTO dto)
        {
            if (dto == null) return null;

            var entity = new tblCompany();

            entity.CompanyID = dto.CompanyID;
            entity.CompanyName = dto.CompanyName;
            entity.ComapnyCode = dto.ComapnyCode;
            entity.OwnerName = dto.OwnerName;
            entity.StartDate = dto.StartDate;
            entity.Address = dto.Address;
            entity.ContactPersonName = dto.ContactPersonName;
            entity.CreationDate = dto.CreationDate;
            entity.InvestmentAmount = dto.InvestmentAmount;
            entity.PANNo = dto.PANNo;
            entity.CSTNo = dto.CSTNo;
            entity.ECCNo = dto.ECCNo;
            entity.SMSNO = dto.SMSNO;
            entity.IsActive = dto.IsActive;
            entity.CreatedBy = dto.CreatedBy;
            entity.CreatedDateTime = dto.CreatedDateTime;
            entity.UpdatedBy = dto.UpdatedBy;
            entity.UpdatedDateTime = dto.UpdatedDateTime;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tblCompany"/> to an instance of <see cref="tblCompanyDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tblCompany"/> to convert.</param>
        public static tblCompanyDTO ToDTO(this tblCompany entity)
        {
            if (entity == null) return null;

            var dto = new tblCompanyDTO();

            dto.CompanyID = entity.CompanyID;
            dto.CompanyName = entity.CompanyName;
            dto.ComapnyCode = entity.ComapnyCode;
            dto.OwnerName = entity.OwnerName;
            dto.StartDate = entity.StartDate;
            dto.Address = entity.Address;
            dto.ContactPersonName = entity.ContactPersonName;
            dto.CreationDate = entity.CreationDate;
            dto.InvestmentAmount = entity.InvestmentAmount;
            dto.PANNo = entity.PANNo;
            dto.CSTNo = entity.CSTNo;
            dto.ECCNo = entity.ECCNo;
            dto.SMSNO = entity.SMSNO;
            dto.IsActive = entity.IsActive;
            dto.CreatedBy = entity.CreatedBy;
            dto.CreatedDateTime = entity.CreatedDateTime;
            dto.UpdatedBy = entity.UpdatedBy;
            dto.UpdatedDateTime = entity.UpdatedDateTime;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tblCompanyDTO"/> to an instance of <see cref="tblCompany"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tblCompany> ToEntities(this IEnumerable<tblCompanyDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tblCompany"/> to an instance of <see cref="tblCompanyDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tblCompanyDTO> ToDTOs(this IEnumerable<tblCompany> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
