//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-08 - 11:39:08
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using LoomsManagement.Domain.DTO;
using LoomsManagement.Database.ORM;

namespace LoomsManagement.DAL.Assemblers
{

    /// <summary>
    /// Assembler for <see cref="tblLoomProcess"/> and <see cref="tblLoomProcessDTO"/>.
    /// </summary>
    public static partial class tblLoomProcessAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tblLoomProcessDTO"/> converted from <see cref="tblLoomProcess"/>.</param>
        static partial void OnDTO(this tblLoomProcess entity, tblLoomProcessDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tblLoomProcess"/> converted from <see cref="tblLoomProcessDTO"/>.</param>
        static partial void OnEntity(this tblLoomProcessDTO dto, tblLoomProcess entity);

        /// <summary>
        /// Converts this instance of <see cref="tblLoomProcessDTO"/> to an instance of <see cref="tblLoomProcess"/>.
        /// </summary>
        /// <param name="dto"><see cref="tblLoomProcessDTO"/> to convert.</param>
        public static tblLoomProcess ToEntity(this tblLoomProcessDTO dto)
        {
            if (dto == null) return null;

            var entity = new tblLoomProcess();

            entity.LoomProcessID = dto.LoomProcessID;
            entity.BeemProcessID = dto.BeemProcessID;
            entity.MachineID = dto.MachineID;
            entity.NoofTFORole = dto.NoofTFORole;
            entity.CreatoinDateTime = dto.CreatoinDateTime;
            entity.IsActive = dto.IsActive;
            entity.CreatedBy = dto.CreatedBy;
            entity.CreatedDateTime = dto.CreatedDateTime;
            entity.UpdatedBy = dto.UpdatedBy;
            entity.UpdatedDateTime = dto.UpdatedDateTime;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tblLoomProcess"/> to an instance of <see cref="tblLoomProcessDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tblLoomProcess"/> to convert.</param>
        public static tblLoomProcessDTO ToDTO(this tblLoomProcess entity)
        {
            if (entity == null) return null;

            var dto = new tblLoomProcessDTO();

            dto.LoomProcessID = entity.LoomProcessID;
            dto.BeemProcessID = entity.BeemProcessID;
            dto.MachineID = entity.MachineID;
            dto.NoofTFORole = entity.NoofTFORole;
            dto.CreatoinDateTime = entity.CreatoinDateTime;
            dto.IsActive = entity.IsActive;
            dto.CreatedBy = entity.CreatedBy;
            dto.CreatedDateTime = entity.CreatedDateTime;
            dto.UpdatedBy = entity.UpdatedBy;
            dto.UpdatedDateTime = entity.UpdatedDateTime;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tblLoomProcessDTO"/> to an instance of <see cref="tblLoomProcess"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tblLoomProcess> ToEntities(this IEnumerable<tblLoomProcessDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tblLoomProcess"/> to an instance of <see cref="tblLoomProcessDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tblLoomProcessDTO> ToDTOs(this IEnumerable<tblLoomProcess> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
