//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-08 - 11:39:09
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using LoomsManagement.Domain.DTO;
using LoomsManagement.Database.ORM;

namespace LoomsManagement.DAL.Assemblers
{

    /// <summary>
    /// Assembler for <see cref="tblLoomProcessWork"/> and <see cref="tblLoomProcessWorkDTO"/>.
    /// </summary>
    public static partial class tblLoomProcessWorkAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tblLoomProcessWorkDTO"/> converted from <see cref="tblLoomProcessWork"/>.</param>
        static partial void OnDTO(this tblLoomProcessWork entity, tblLoomProcessWorkDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tblLoomProcessWork"/> converted from <see cref="tblLoomProcessWorkDTO"/>.</param>
        static partial void OnEntity(this tblLoomProcessWorkDTO dto, tblLoomProcessWork entity);

        /// <summary>
        /// Converts this instance of <see cref="tblLoomProcessWorkDTO"/> to an instance of <see cref="tblLoomProcessWork"/>.
        /// </summary>
        /// <param name="dto"><see cref="tblLoomProcessWorkDTO"/> to convert.</param>
        public static tblLoomProcessWork ToEntity(this tblLoomProcessWorkDTO dto)
        {
            if (dto == null) return null;

            var entity = new tblLoomProcessWork();

            entity.LoomProcessWorkID = dto.LoomProcessWorkID;
            entity.LoomProcessID = dto.LoomProcessID;
            entity.EmployeeID = dto.EmployeeID;
            entity.WorkingDate = dto.WorkingDate;
            entity.StartTime = dto.StartTime;
            entity.EndTime = dto.EndTime;
            entity.Shift = dto.Shift;
            entity.MTRStart = dto.MTRStart;
            entity.MTREnd = dto.MTREnd;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tblLoomProcessWork"/> to an instance of <see cref="tblLoomProcessWorkDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tblLoomProcessWork"/> to convert.</param>
        public static tblLoomProcessWorkDTO ToDTO(this tblLoomProcessWork entity)
        {
            if (entity == null) return null;

            var dto = new tblLoomProcessWorkDTO();

            dto.LoomProcessWorkID = entity.LoomProcessWorkID;
            dto.LoomProcessID = entity.LoomProcessID;
            dto.EmployeeID = entity.EmployeeID;
            dto.WorkingDate = entity.WorkingDate;
            dto.StartTime = entity.StartTime;
            dto.EndTime = entity.EndTime;
            dto.Shift = entity.Shift;
            dto.MTRStart = entity.MTRStart;
            dto.MTREnd = entity.MTREnd;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tblLoomProcessWorkDTO"/> to an instance of <see cref="tblLoomProcessWork"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tblLoomProcessWork> ToEntities(this IEnumerable<tblLoomProcessWorkDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tblLoomProcessWork"/> to an instance of <see cref="tblLoomProcessWorkDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tblLoomProcessWorkDTO> ToDTOs(this IEnumerable<tblLoomProcessWork> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
