//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-08 - 11:39:09
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using LoomsManagement.Domain.DTO;
using LoomsManagement.Database.ORM;

namespace LoomsManagement.DAL.Assemblers
{

    /// <summary>
    /// Assembler for <see cref="tblMandingProcess"/> and <see cref="tblMandingProcessDTO"/>.
    /// </summary>
    public static partial class tblMandingProcessAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tblMandingProcessDTO"/> converted from <see cref="tblMandingProcess"/>.</param>
        static partial void OnDTO(this tblMandingProcess entity, tblMandingProcessDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tblMandingProcess"/> converted from <see cref="tblMandingProcessDTO"/>.</param>
        static partial void OnEntity(this tblMandingProcessDTO dto, tblMandingProcess entity);

        /// <summary>
        /// Converts this instance of <see cref="tblMandingProcessDTO"/> to an instance of <see cref="tblMandingProcess"/>.
        /// </summary>
        /// <param name="dto"><see cref="tblMandingProcessDTO"/> to convert.</param>
        public static tblMandingProcess ToEntity(this tblMandingProcessDTO dto)
        {
            if (dto == null) return null;

            var entity = new tblMandingProcess();

            entity.MendingID = dto.MendingID;
            entity.TakaNo = dto.TakaNo;
            entity.EmployeeID = dto.EmployeeID;
            entity.Grade = dto.Grade;
            entity.StartDateTime = dto.StartDateTime;
            entity.EndDateTime = dto.EndDateTime;
            entity.TotalMeter = dto.TotalMeter;
            entity.TotalNoOfFaults = dto.TotalNoOfFaults;
            entity.IsActive = dto.IsActive;
            entity.CreateBy = dto.CreateBy;
            entity.CreationDateTime = dto.CreationDateTime;
            entity.UpdateBy = dto.UpdateBy;
            entity.UpdationDateTime = dto.UpdationDateTime;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tblMandingProcess"/> to an instance of <see cref="tblMandingProcessDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tblMandingProcess"/> to convert.</param>
        public static tblMandingProcessDTO ToDTO(this tblMandingProcess entity)
        {
            if (entity == null) return null;

            var dto = new tblMandingProcessDTO();

            dto.MendingID = entity.MendingID;
            dto.TakaNo = entity.TakaNo;
            dto.EmployeeID = entity.EmployeeID;
            dto.Grade = entity.Grade;
            dto.StartDateTime = entity.StartDateTime;
            dto.EndDateTime = entity.EndDateTime;
            dto.TotalMeter = entity.TotalMeter;
            dto.TotalNoOfFaults = entity.TotalNoOfFaults;
            dto.IsActive = entity.IsActive;
            dto.CreateBy = entity.CreateBy;
            dto.CreationDateTime = entity.CreationDateTime;
            dto.UpdateBy = entity.UpdateBy;
            dto.UpdationDateTime = entity.UpdationDateTime;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tblMandingProcessDTO"/> to an instance of <see cref="tblMandingProcess"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tblMandingProcess> ToEntities(this IEnumerable<tblMandingProcessDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tblMandingProcess"/> to an instance of <see cref="tblMandingProcessDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tblMandingProcessDTO> ToDTOs(this IEnumerable<tblMandingProcess> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
