//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-08 - 11:39:10
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using LoomsManagement.Domain.DTO;
using LoomsManagement.Database.ORM;

namespace LoomsManagement.DAL.Assemblers
{

    /// <summary>
    /// Assembler for <see cref="tblMendingDetailsProcess"/> and <see cref="tblMendingDetailsProcessDTO"/>.
    /// </summary>
    public static partial class tblMendingDetailsProcessAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tblMendingDetailsProcessDTO"/> converted from <see cref="tblMendingDetailsProcess"/>.</param>
        static partial void OnDTO(this tblMendingDetailsProcess entity, tblMendingDetailsProcessDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tblMendingDetailsProcess"/> converted from <see cref="tblMendingDetailsProcessDTO"/>.</param>
        static partial void OnEntity(this tblMendingDetailsProcessDTO dto, tblMendingDetailsProcess entity);

        /// <summary>
        /// Converts this instance of <see cref="tblMendingDetailsProcessDTO"/> to an instance of <see cref="tblMendingDetailsProcess"/>.
        /// </summary>
        /// <param name="dto"><see cref="tblMendingDetailsProcessDTO"/> to convert.</param>
        public static tblMendingDetailsProcess ToEntity(this tblMendingDetailsProcessDTO dto)
        {
            if (dto == null) return null;

            var entity = new tblMendingDetailsProcess();

            entity.MendingDetailsID = dto.MendingDetailsID;
            entity.MendingID = dto.MendingID;
            entity.EmployeeID = dto.EmployeeID;
            entity.StartMeter = dto.StartMeter;
            entity.EndMeter = dto.EndMeter;
            entity.IsActive = dto.IsActive;
            entity.CreateBy = dto.CreateBy;
            entity.CreationDateTime = dto.CreationDateTime;
            entity.UpdateBy = dto.UpdateBy;
            entity.UpdationDateTime = dto.UpdationDateTime;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tblMendingDetailsProcess"/> to an instance of <see cref="tblMendingDetailsProcessDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tblMendingDetailsProcess"/> to convert.</param>
        public static tblMendingDetailsProcessDTO ToDTO(this tblMendingDetailsProcess entity)
        {
            if (entity == null) return null;

            var dto = new tblMendingDetailsProcessDTO();

            dto.MendingDetailsID = entity.MendingDetailsID;
            dto.MendingID = entity.MendingID;
            dto.EmployeeID = entity.EmployeeID;
            dto.StartMeter = entity.StartMeter;
            dto.EndMeter = entity.EndMeter;
            dto.IsActive = entity.IsActive;
            dto.CreateBy = entity.CreateBy;
            dto.CreationDateTime = entity.CreationDateTime;
            dto.UpdateBy = entity.UpdateBy;
            dto.UpdationDateTime = entity.UpdationDateTime;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tblMendingDetailsProcessDTO"/> to an instance of <see cref="tblMendingDetailsProcess"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tblMendingDetailsProcess> ToEntities(this IEnumerable<tblMendingDetailsProcessDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tblMendingDetailsProcess"/> to an instance of <see cref="tblMendingDetailsProcessDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tblMendingDetailsProcessDTO> ToDTOs(this IEnumerable<tblMendingDetailsProcess> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
