//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-08 - 11:39:10
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using LoomsManagement.Domain.DTO;
using LoomsManagement.Database.ORM;

namespace LoomsManagement.DAL.Assemblers
{

    /// <summary>
    /// Assembler for <see cref="tblPenaltyMST"/> and <see cref="tblPenaltyMSTDTO"/>.
    /// </summary>
    public static partial class tblPenaltyMSTAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tblPenaltyMSTDTO"/> converted from <see cref="tblPenaltyMST"/>.</param>
        static partial void OnDTO(this tblPenaltyMST entity, tblPenaltyMSTDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tblPenaltyMST"/> converted from <see cref="tblPenaltyMSTDTO"/>.</param>
        static partial void OnEntity(this tblPenaltyMSTDTO dto, tblPenaltyMST entity);

        /// <summary>
        /// Converts this instance of <see cref="tblPenaltyMSTDTO"/> to an instance of <see cref="tblPenaltyMST"/>.
        /// </summary>
        /// <param name="dto"><see cref="tblPenaltyMSTDTO"/> to convert.</param>
        public static tblPenaltyMST ToEntity(this tblPenaltyMSTDTO dto)
        {
            if (dto == null) return null;

            var entity = new tblPenaltyMST();

            entity.PenaltyID = dto.PenaltyID;
            entity.PenaltyCode = dto.PenaltyCode;
            entity.PenaltyName = dto.PenaltyName;
            entity.Description = dto.Description;
            entity.IsActive = dto.IsActive;
            entity.CreateBy = dto.CreateBy;
            entity.CreationDateTime = dto.CreationDateTime;
            entity.UpdateBy = dto.UpdateBy;
            entity.UpdationDateTime = dto.UpdationDateTime;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tblPenaltyMST"/> to an instance of <see cref="tblPenaltyMSTDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tblPenaltyMST"/> to convert.</param>
        public static tblPenaltyMSTDTO ToDTO(this tblPenaltyMST entity)
        {
            if (entity == null) return null;

            var dto = new tblPenaltyMSTDTO();

            dto.PenaltyID = entity.PenaltyID;
            dto.PenaltyCode = entity.PenaltyCode;
            dto.PenaltyName = entity.PenaltyName;
            dto.Description = entity.Description;
            dto.IsActive = entity.IsActive;
            dto.CreateBy = entity.CreateBy;
            dto.CreationDateTime = entity.CreationDateTime;
            dto.UpdateBy = entity.UpdateBy;
            dto.UpdationDateTime = entity.UpdationDateTime;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tblPenaltyMSTDTO"/> to an instance of <see cref="tblPenaltyMST"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tblPenaltyMST> ToEntities(this IEnumerable<tblPenaltyMSTDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tblPenaltyMST"/> to an instance of <see cref="tblPenaltyMSTDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tblPenaltyMSTDTO> ToDTOs(this IEnumerable<tblPenaltyMST> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
