//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-08 - 11:39:12
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using LoomsManagement.Domain.DTO;
using LoomsManagement.Database.ORM;

namespace LoomsManagement.DAL.Assemblers
{

    /// <summary>
    /// Assembler for <see cref="tblWithdrownMST"/> and <see cref="tblWithdrownMSTDTO"/>.
    /// </summary>
    public static partial class tblWithdrownMSTAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tblWithdrownMSTDTO"/> converted from <see cref="tblWithdrownMST"/>.</param>
        static partial void OnDTO(this tblWithdrownMST entity, tblWithdrownMSTDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tblWithdrownMST"/> converted from <see cref="tblWithdrownMSTDTO"/>.</param>
        static partial void OnEntity(this tblWithdrownMSTDTO dto, tblWithdrownMST entity);

        /// <summary>
        /// Converts this instance of <see cref="tblWithdrownMSTDTO"/> to an instance of <see cref="tblWithdrownMST"/>.
        /// </summary>
        /// <param name="dto"><see cref="tblWithdrownMSTDTO"/> to convert.</param>
        public static tblWithdrownMST ToEntity(this tblWithdrownMSTDTO dto)
        {
            if (dto == null) return null;

            var entity = new tblWithdrownMST();

            entity.WithdrownID = dto.WithdrownID;
            entity.EmployeeID = dto.EmployeeID;
            entity.Remarks = dto.Remarks;
            entity.WithdrownAmount = dto.WithdrownAmount;
            entity.WithdrownDate = dto.WithdrownDate;
            entity.ReturnDate = dto.ReturnDate;
            entity.ISStatus = dto.ISStatus;
            entity.IsActive = dto.IsActive;
            entity.CreateBy = dto.CreateBy;
            entity.CreationDateTime = dto.CreationDateTime;
            entity.UpdateBy = dto.UpdateBy;
            entity.UpdationDateTime = dto.UpdationDateTime;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tblWithdrownMST"/> to an instance of <see cref="tblWithdrownMSTDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tblWithdrownMST"/> to convert.</param>
        public static tblWithdrownMSTDTO ToDTO(this tblWithdrownMST entity)
        {
            if (entity == null) return null;

            var dto = new tblWithdrownMSTDTO();

            dto.WithdrownID = entity.WithdrownID;
            dto.EmployeeID = entity.EmployeeID;
            dto.Remarks = entity.Remarks;
            dto.WithdrownAmount = entity.WithdrownAmount;
            dto.WithdrownDate = entity.WithdrownDate;
            dto.ReturnDate = entity.ReturnDate;
            dto.ISStatus = entity.ISStatus;
            dto.IsActive = entity.IsActive;
            dto.CreateBy = entity.CreateBy;
            dto.CreationDateTime = entity.CreationDateTime;
            dto.UpdateBy = entity.UpdateBy;
            dto.UpdationDateTime = entity.UpdationDateTime;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tblWithdrownMSTDTO"/> to an instance of <see cref="tblWithdrownMST"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tblWithdrownMST> ToEntities(this IEnumerable<tblWithdrownMSTDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tblWithdrownMST"/> to an instance of <see cref="tblWithdrownMSTDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tblWithdrownMSTDTO> ToDTOs(this IEnumerable<tblWithdrownMST> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
