//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-08 - 11:39:13
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using LoomsManagement.Domain.DTO;
using LoomsManagement.Database.ORM;

namespace LoomsManagement.DAL.Assemblers
{

    /// <summary>
    /// Assembler for <see cref="tblYarnPurchaseItem"/> and <see cref="tblYarnPurchaseItemDTO"/>.
    /// </summary>
    public static partial class tblYarnPurchaseItemAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tblYarnPurchaseItemDTO"/> converted from <see cref="tblYarnPurchaseItem"/>.</param>
        static partial void OnDTO(this tblYarnPurchaseItem entity, tblYarnPurchaseItemDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tblYarnPurchaseItem"/> converted from <see cref="tblYarnPurchaseItemDTO"/>.</param>
        static partial void OnEntity(this tblYarnPurchaseItemDTO dto, tblYarnPurchaseItem entity);

        /// <summary>
        /// Converts this instance of <see cref="tblYarnPurchaseItemDTO"/> to an instance of <see cref="tblYarnPurchaseItem"/>.
        /// </summary>
        /// <param name="dto"><see cref="tblYarnPurchaseItemDTO"/> to convert.</param>
        public static tblYarnPurchaseItem ToEntity(this tblYarnPurchaseItemDTO dto)
        {
            if (dto == null) return null;

            var entity = new tblYarnPurchaseItem();

            entity.PurchaseItemID = dto.PurchaseItemID;
            entity.PurchaseID = dto.PurchaseID;
            entity.YarnID = dto.YarnID;
            entity.YarnPackageTypeID = dto.YarnPackageTypeID;
            entity.PurchaseDate = dto.PurchaseDate;
            entity.BoxNo = dto.BoxNo;
            entity.GrossWeight = dto.GrossWeight;
            entity.TareWeight = dto.TareWeight;
            entity.NetWeight = dto.NetWeight;
            entity.Cheese = dto.Cheese;
            entity.EmployeeID = dto.EmployeeID;
            entity.YarnQualityID = dto.YarnQualityID;
            entity.YarnTypeID = dto.YarnTypeID;
            entity.IsActive = dto.IsActive;
            entity.UpdateBy = dto.UpdateBy;
            entity.CreateBy = dto.CreateBy;
            entity.UpdationDateTime = dto.UpdationDateTime;
            entity.CreationDateTIme = dto.CreationDateTIme;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tblYarnPurchaseItem"/> to an instance of <see cref="tblYarnPurchaseItemDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tblYarnPurchaseItem"/> to convert.</param>
        public static tblYarnPurchaseItemDTO ToDTO(this tblYarnPurchaseItem entity)
        {
            if (entity == null) return null;

            var dto = new tblYarnPurchaseItemDTO();

            dto.PurchaseItemID = entity.PurchaseItemID;
            dto.PurchaseID = entity.PurchaseID;
            dto.YarnID = entity.YarnID;
            dto.YarnPackageTypeID = entity.YarnPackageTypeID;
            dto.PurchaseDate = entity.PurchaseDate;
            dto.BoxNo = entity.BoxNo;
            dto.GrossWeight = entity.GrossWeight;
            dto.TareWeight = entity.TareWeight;
            dto.NetWeight = entity.NetWeight;
            dto.Cheese = entity.Cheese;
            dto.EmployeeID = entity.EmployeeID;
            dto.YarnQualityID = entity.YarnQualityID;
            dto.YarnTypeID = entity.YarnTypeID;
            dto.IsActive = entity.IsActive;
            dto.UpdateBy = entity.UpdateBy;
            dto.CreateBy = entity.CreateBy;
            dto.UpdationDateTime = entity.UpdationDateTime;
            dto.CreationDateTIme = entity.CreationDateTIme;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tblYarnPurchaseItemDTO"/> to an instance of <see cref="tblYarnPurchaseItem"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tblYarnPurchaseItem> ToEntities(this IEnumerable<tblYarnPurchaseItemDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tblYarnPurchaseItem"/> to an instance of <see cref="tblYarnPurchaseItemDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tblYarnPurchaseItemDTO> ToDTOs(this IEnumerable<tblYarnPurchaseItem> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
