//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-08 - 11:39:14
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using LoomsManagement.Domain.DTO;
using LoomsManagement.Database.ORM;

namespace LoomsManagement.DAL.Assemblers
{

    /// <summary>
    /// Assembler for <see cref="WithdrownReturnMST"/> and <see cref="WithdrownReturnMSTDTO"/>.
    /// </summary>
    public static partial class WithdrownReturnMSTAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="WithdrownReturnMSTDTO"/> converted from <see cref="WithdrownReturnMST"/>.</param>
        static partial void OnDTO(this WithdrownReturnMST entity, WithdrownReturnMSTDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="WithdrownReturnMST"/> converted from <see cref="WithdrownReturnMSTDTO"/>.</param>
        static partial void OnEntity(this WithdrownReturnMSTDTO dto, WithdrownReturnMST entity);

        /// <summary>
        /// Converts this instance of <see cref="WithdrownReturnMSTDTO"/> to an instance of <see cref="WithdrownReturnMST"/>.
        /// </summary>
        /// <param name="dto"><see cref="WithdrownReturnMSTDTO"/> to convert.</param>
        public static WithdrownReturnMST ToEntity(this WithdrownReturnMSTDTO dto)
        {
            if (dto == null) return null;

            var entity = new WithdrownReturnMST();

            entity.WithdrownReturnID = dto.WithdrownReturnID;
            entity.Date = dto.Date;
            entity.EmployeeID = dto.EmployeeID;
            entity.ReturnType = dto.ReturnType;
            entity.SalaryID = dto.SalaryID;
            entity.Amount = dto.Amount;
            entity.Remark = dto.Remark;
            entity.IsActive = dto.IsActive;
            entity.CreateBy = dto.CreateBy;
            entity.CreationDateTime = dto.CreationDateTime;
            entity.UpdateBy = dto.UpdateBy;
            entity.UpdationDateTime = dto.UpdationDateTime;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="WithdrownReturnMST"/> to an instance of <see cref="WithdrownReturnMSTDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="WithdrownReturnMST"/> to convert.</param>
        public static WithdrownReturnMSTDTO ToDTO(this WithdrownReturnMST entity)
        {
            if (entity == null) return null;

            var dto = new WithdrownReturnMSTDTO();

            dto.WithdrownReturnID = entity.WithdrownReturnID;
            dto.Date = entity.Date;
            dto.EmployeeID = entity.EmployeeID;
            dto.ReturnType = entity.ReturnType;
            dto.SalaryID = entity.SalaryID;
            dto.Amount = entity.Amount;
            dto.Remark = entity.Remark;
            dto.IsActive = entity.IsActive;
            dto.CreateBy = entity.CreateBy;
            dto.CreationDateTime = entity.CreationDateTime;
            dto.UpdateBy = entity.UpdateBy;
            dto.UpdationDateTime = entity.UpdationDateTime;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="WithdrownReturnMSTDTO"/> to an instance of <see cref="WithdrownReturnMST"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<WithdrownReturnMST> ToEntities(this IEnumerable<WithdrownReturnMSTDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="WithdrownReturnMST"/> to an instance of <see cref="WithdrownReturnMSTDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<WithdrownReturnMSTDTO> ToDTOs(this IEnumerable<WithdrownReturnMST> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
