//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoomsManagement.Database.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBankMST
    {
        public tblBankMST()
        {
            this.tblBranchMSTs = new HashSet<tblBranchMST>();
        }
    
        public long BankID { get; set; }
        public string BankName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdationDateTime { get; set; }
    
        public virtual ICollection<tblBranchMST> tblBranchMSTs { get; set; }
    }
}
