//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoomsManagement.Database.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBeamMST
    {
        public long BeemID { get; set; }
        public Nullable<long> CompnayID { get; set; }
        public Nullable<int> WrapperPartyName { get; set; }
        public Nullable<int> JobberPartyName { get; set; }
        public Nullable<System.DateTime> BeemDate { get; set; }
        public Nullable<int> YarnQuality { get; set; }
        public Nullable<int> GrayQuality { get; set; }
        public Nullable<int> TarNo { get; set; }
        public Nullable<double> Meters { get; set; }
        public Nullable<int> Taka { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> ProductionMeters { get; set; }
        public Nullable<int> ProductionTaka { get; set; }
        public Nullable<double> PipeWeight { get; set; }
        public Nullable<System.DateTime> LoadingDate { get; set; }
        public Nullable<double> MinStragy { get; set; }
        public Nullable<int> MachinNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> BhidanStatus { get; set; }
        public Nullable<System.DateTime> BhidanDate { get; set; }
        public Nullable<int> PasaraiName { get; set; }
        public Nullable<double> Count { get; set; }
        public Nullable<System.DateTime> IssuDate { get; set; }
        public Nullable<bool> TakaMeter { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> MeterConsumption { get; set; }
        public Nullable<double> RPM { get; set; }
        public Nullable<double> Pick { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdationDateTime { get; set; }
    }
}
