//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoomsManagement.Database.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBolierProcessDetail
    {
        public long BoilerProcessDetailsID { get; set; }
        public Nullable<long> BoilerProcessID { get; set; }
        public Nullable<long> TFORoleProcessID { get; set; }
        public Nullable<int> IssueNoOfTFORoles { get; set; }
        public Nullable<double> IssueWeights { get; set; }
        public Nullable<long> YarnQualityID { get; set; }
        public Nullable<long> YarnTypeID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tblBoilerProcess tblBoilerProcess { get; set; }
        public virtual tblTFOProcess tblTFOProcess { get; set; }
    }
}
