//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoomsManagement.Database.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeTypeMST
    {
        public tblEmployeeTypeMST()
        {
            this.tblEmployees = new HashSet<tblEmployee>();
        }
    
        public long EmployeeTypeID { get; set; }
        public string TypeName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
    
        public virtual ICollection<tblEmployee> tblEmployees { get; set; }
    }
}
