//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoomsManagement.Database.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTFOProcess
    {
        public tblTFOProcess()
        {
            this.tblBemProcessDetails = new HashSet<tblBemProcessDetail>();
            this.tblBolierProcessDetails = new HashSet<tblBolierProcessDetail>();
        }
    
        public long TFORoleProcessId { get; set; }
        public Nullable<int> WindingProcessId { get; set; }
        public Nullable<int> PurchaseItemID { get; set; }
        public Nullable<int> MachineId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string Shift { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<int> IssueNoOfCopes { get; set; }
        public Nullable<double> IssueWights { get; set; }
        public Nullable<double> NoofTFORole { get; set; }
        public Nullable<int> ProducttionNoOfTFORoles { get; set; }
        public Nullable<double> ProducttionWights { get; set; }
        public string QualityName { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<int> YarnQualityId { get; set; }
        public Nullable<int> YarnTypeId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdationDateTime { get; set; }
        public Nullable<System.DateTime> CreationDateTIme { get; set; }
    
        public virtual ICollection<tblBemProcessDetail> tblBemProcessDetails { get; set; }
        public virtual ICollection<tblBolierProcessDetail> tblBolierProcessDetails { get; set; }
        public virtual tblWindingWork tblWindingWork { get; set; }
    }
}
