//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoomsManagement.Database.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblYarnQualityMST
    {
        public tblYarnQualityMST()
        {
            this.tblYarnPurchaseItems = new HashSet<tblYarnPurchaseItem>();
            this.tblYarnPurchaseItems1 = new HashSet<tblYarnPurchaseItem>();
            this.tblYarnTypeMSTs = new HashSet<tblYarnTypeMST>();
        }
    
        public long YarnQualityID { get; set; }
        public string YarnQualityName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdationDateTime { get; set; }
    
        public virtual ICollection<tblYarnPurchaseItem> tblYarnPurchaseItems { get; set; }
        public virtual ICollection<tblYarnPurchaseItem> tblYarnPurchaseItems1 { get; set; }
        public virtual ICollection<tblYarnTypeMST> tblYarnTypeMSTs { get; set; }
    }
}
