//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoomsManagement.Database.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblYarnTypeMST
    {
        public tblYarnTypeMST()
        {
            this.tblYarnPurchaseItems = new HashSet<tblYarnPurchaseItem>();
        }
    
        public long YarnTypeID { get; set; }
        public string YarnTypeName { get; set; }
        public Nullable<long> YarnQualityID { get; set; }
        public string Denier { get; set; }
        public Nullable<int> NumberOfFilaments { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdationDateTime { get; set; }
        public Nullable<System.DateTime> CreationDateTIme { get; set; }
    
        public virtual ICollection<tblYarnPurchaseItem> tblYarnPurchaseItems { get; set; }
        public virtual tblYarnQualityMST tblYarnQualityMST { get; set; }
    }
}
