//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-09 - 14:23:56
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using LoomsManagement.Domain.DTO;
using LoomsManagement.DAL.ORM;

namespace LoomsManagement.DAL
{

    /// <summary>
    /// Assembler for <see cref="tblAttendanceMST"/> and <see cref="tblAttendanceMSTDTO"/>.
    /// </summary>
    public static partial class tblAttendanceMSTAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tblAttendanceMSTDTO"/> converted from <see cref="tblAttendanceMST"/>.</param>
        static partial void OnDTO(this tblAttendanceMST entity, tblAttendanceMSTDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tblAttendanceMST"/> converted from <see cref="tblAttendanceMSTDTO"/>.</param>
        static partial void OnEntity(this tblAttendanceMSTDTO dto, tblAttendanceMST entity);

        /// <summary>
        /// Converts this instance of <see cref="tblAttendanceMSTDTO"/> to an instance of <see cref="tblAttendanceMST"/>.
        /// </summary>
        /// <param name="dto"><see cref="tblAttendanceMSTDTO"/> to convert.</param>
        public static tblAttendanceMST ToEntity(this tblAttendanceMSTDTO dto)
        {
            if (dto == null) return null;

            var entity = new tblAttendanceMST();

            entity.AttendanceID = dto.AttendanceID;
            entity.EmployeeID = dto.EmployeeID;
            entity.StartTime = dto.StartTime;
            entity.EndTime = dto.EndTime;
            entity.MeterWorked = dto.MeterWorked;
            entity.IsActive = dto.IsActive;
            entity.IsDelete = dto.IsDelete;
            entity.CreateBy = dto.CreateBy;
            entity.CreationDateTime = dto.CreationDateTime;
            entity.UpdateBy = dto.UpdateBy;
            entity.UpdationDateTime = dto.UpdationDateTime;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tblAttendanceMST"/> to an instance of <see cref="tblAttendanceMSTDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tblAttendanceMST"/> to convert.</param>
        public static tblAttendanceMSTDTO ToDTO(this tblAttendanceMST entity)
        {
            if (entity == null) return null;

            var dto = new tblAttendanceMSTDTO();

            dto.AttendanceID = entity.AttendanceID;
            dto.EmployeeID = entity.EmployeeID;
            dto.StartTime = entity.StartTime;
            dto.EndTime = entity.EndTime;
            dto.MeterWorked = entity.MeterWorked;
            dto.IsActive = entity.IsActive;
            dto.IsDelete = entity.IsDelete;
            dto.CreateBy = entity.CreateBy;
            dto.CreationDateTime = entity.CreationDateTime;
            dto.UpdateBy = entity.UpdateBy;
            dto.UpdationDateTime = entity.UpdationDateTime;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tblAttendanceMSTDTO"/> to an instance of <see cref="tblAttendanceMST"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tblAttendanceMST> ToEntities(this IEnumerable<tblAttendanceMSTDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tblAttendanceMST"/> to an instance of <see cref="tblAttendanceMSTDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tblAttendanceMSTDTO> ToDTOs(this IEnumerable<tblAttendanceMST> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
