//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-09 - 14:23:57
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using LoomsManagement.Domain.DTO;
using LoomsManagement.DAL.ORM;

namespace LoomsManagement.DAL
{

    /// <summary>
    /// Assembler for <see cref="tblBemProcessDetail"/> and <see cref="tblBemProcessDetailDTO"/>.
    /// </summary>
    public static partial class tblBemProcessDetailAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tblBemProcessDetailDTO"/> converted from <see cref="tblBemProcessDetail"/>.</param>
        static partial void OnDTO(this tblBemProcessDetail entity, tblBemProcessDetailDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tblBemProcessDetail"/> converted from <see cref="tblBemProcessDetailDTO"/>.</param>
        static partial void OnEntity(this tblBemProcessDetailDTO dto, tblBemProcessDetail entity);

        /// <summary>
        /// Converts this instance of <see cref="tblBemProcessDetailDTO"/> to an instance of <see cref="tblBemProcessDetail"/>.
        /// </summary>
        /// <param name="dto"><see cref="tblBemProcessDetailDTO"/> to convert.</param>
        public static tblBemProcessDetail ToEntity(this tblBemProcessDetailDTO dto)
        {
            if (dto == null) return null;

            var entity = new tblBemProcessDetail();

            entity.BemProcessDetailsID = dto.BemProcessDetailsID;
            entity.BemProcessID = dto.BemProcessID;
            entity.TFORoleProcessID = dto.TFORoleProcessID;
            entity.IssueNoOFCopes = dto.IssueNoOFCopes;
            entity.IssueWeights = dto.IssueWeights;
            entity.YarnQualityID = dto.YarnQualityID;
            entity.YarnTypeID = dto.YarnTypeID;
            entity.IsDelete = dto.IsDelete;
            entity.IsActive = dto.IsActive;
            entity.CreateBy = dto.CreateBy;
            entity.CreationDateTime = dto.CreationDateTime;
            entity.UpdateBy = dto.UpdateBy;
            entity.UpdationDateTime = dto.UpdationDateTime;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tblBemProcessDetail"/> to an instance of <see cref="tblBemProcessDetailDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tblBemProcessDetail"/> to convert.</param>
        public static tblBemProcessDetailDTO ToDTO(this tblBemProcessDetail entity)
        {
            if (entity == null) return null;

            var dto = new tblBemProcessDetailDTO();

            dto.BemProcessDetailsID = entity.BemProcessDetailsID;
            dto.BemProcessID = entity.BemProcessID;
            dto.TFORoleProcessID = entity.TFORoleProcessID;
            dto.IssueNoOFCopes = entity.IssueNoOFCopes;
            dto.IssueWeights = entity.IssueWeights;
            dto.YarnQualityID = entity.YarnQualityID;
            dto.YarnTypeID = entity.YarnTypeID;
            dto.IsDelete = entity.IsDelete;
            dto.IsActive = entity.IsActive;
            dto.CreateBy = entity.CreateBy;
            dto.CreationDateTime = entity.CreationDateTime;
            dto.UpdateBy = entity.UpdateBy;
            dto.UpdationDateTime = entity.UpdationDateTime;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tblBemProcessDetailDTO"/> to an instance of <see cref="tblBemProcessDetail"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tblBemProcessDetail> ToEntities(this IEnumerable<tblBemProcessDetailDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tblBemProcessDetail"/> to an instance of <see cref="tblBemProcessDetailDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tblBemProcessDetailDTO> ToDTOs(this IEnumerable<tblBemProcessDetail> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
