//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-09 - 14:23:59
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using LoomsManagement.Domain.DTO;
using LoomsManagement.DAL.ORM;

namespace LoomsManagement.DAL
{

    /// <summary>
    /// Assembler for <see cref="tblBrokersMST"/> and <see cref="tblBrokersMSTDTO"/>.
    /// </summary>
    public static partial class tblBrokersMSTAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tblBrokersMSTDTO"/> converted from <see cref="tblBrokersMST"/>.</param>
        static partial void OnDTO(this tblBrokersMST entity, tblBrokersMSTDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tblBrokersMST"/> converted from <see cref="tblBrokersMSTDTO"/>.</param>
        static partial void OnEntity(this tblBrokersMSTDTO dto, tblBrokersMST entity);

        /// <summary>
        /// Converts this instance of <see cref="tblBrokersMSTDTO"/> to an instance of <see cref="tblBrokersMST"/>.
        /// </summary>
        /// <param name="dto"><see cref="tblBrokersMSTDTO"/> to convert.</param>
        public static tblBrokersMST ToEntity(this tblBrokersMSTDTO dto)
        {
            if (dto == null) return null;

            var entity = new tblBrokersMST();

            entity.BrokerID = dto.BrokerID;
            entity.BrokerName = dto.BrokerName;
            entity.BrokerFirmName = dto.BrokerFirmName;
            entity.Address = dto.Address;
            entity.ContactNo = dto.ContactNo;
            entity.MobileNo = dto.MobileNo;
            entity.DealingIn = dto.DealingIn;
            entity.IsDelete = dto.IsDelete;
            entity.IsActive = dto.IsActive;
            entity.CreateBy = dto.CreateBy;
            entity.CreationDateTime = dto.CreationDateTime;
            entity.UpdateBy = dto.UpdateBy;
            entity.UpdationDateTime = dto.UpdationDateTime;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tblBrokersMST"/> to an instance of <see cref="tblBrokersMSTDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tblBrokersMST"/> to convert.</param>
        public static tblBrokersMSTDTO ToDTO(this tblBrokersMST entity)
        {
            if (entity == null) return null;

            var dto = new tblBrokersMSTDTO();

            dto.BrokerID = entity.BrokerID;
            dto.BrokerName = entity.BrokerName;
            dto.BrokerFirmName = entity.BrokerFirmName;
            dto.Address = entity.Address;
            dto.ContactNo = entity.ContactNo;
            dto.MobileNo = entity.MobileNo;
            dto.DealingIn = entity.DealingIn;
            dto.IsDelete = entity.IsDelete;
            dto.IsActive = entity.IsActive;
            dto.CreateBy = entity.CreateBy;
            dto.CreationDateTime = entity.CreationDateTime;
            dto.UpdateBy = entity.UpdateBy;
            dto.UpdationDateTime = entity.UpdationDateTime;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tblBrokersMSTDTO"/> to an instance of <see cref="tblBrokersMST"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tblBrokersMST> ToEntities(this IEnumerable<tblBrokersMSTDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tblBrokersMST"/> to an instance of <see cref="tblBrokersMSTDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tblBrokersMSTDTO> ToDTOs(this IEnumerable<tblBrokersMST> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
