//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-24 - 22:25:32
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using LoomsManagement.Domain.DTO;
using LoomsManagement.DAL.ORM;

namespace LoomsManagement.DAL
{

    /// <summary>
    /// Assembler for <see cref="tblBeamMST"/> and <see cref="tblBeamMSTDTO"/>.
    /// </summary>
    public static partial class tblBeamMSTAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tblBeamMSTDTO"/> converted from <see cref="tblBeamMST"/>.</param>
        static partial void OnDTO(this tblBeamMST entity, tblBeamMSTDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tblBeamMST"/> converted from <see cref="tblBeamMSTDTO"/>.</param>
        static partial void OnEntity(this tblBeamMSTDTO dto, tblBeamMST entity);

        /// <summary>
        /// Converts this instance of <see cref="tblBeamMSTDTO"/> to an instance of <see cref="tblBeamMST"/>.
        /// </summary>
        /// <param name="dto"><see cref="tblBeamMSTDTO"/> to convert.</param>
        public static tblBeamMST ToEntity(this tblBeamMSTDTO dto)
        {
            if (dto == null) return null;

            var entity = new tblBeamMST();

            entity.BeemID = dto.BeemID;
            entity.CompanyID = dto.CompanyID;
            entity.WrapperPartyName = dto.WrapperPartyName;
            entity.JobberPartyName = dto.JobberPartyName;
            entity.BeemDate = dto.BeemDate;
            entity.YarnQuality = dto.YarnQuality;
            entity.GrayQuality = dto.GrayQuality;
            entity.TarNo = dto.TarNo;
            entity.Meters = dto.Meters;
            entity.Taka = dto.Taka;
            entity.Weight = dto.Weight;
            entity.ProductionMeters = dto.ProductionMeters;
            entity.ProductionTaka = dto.ProductionTaka;
            entity.PipeWeight = dto.PipeWeight;
            entity.LoadingDate = dto.LoadingDate;
            entity.MinStrategy = dto.MinStrategy;
            entity.MachineNo = dto.MachineNo;
            entity.Remarks = dto.Remarks;
            entity.BhidanStatus = dto.BhidanStatus;
            entity.BhidanDate = dto.BhidanDate;
            entity.PasaraiName = dto.PasaraiName;
            entity.Count = dto.Count;
            entity.IssueDate = dto.IssueDate;
            entity.TakaMeter = dto.TakaMeter;
            entity.Rate = dto.Rate;
            entity.Amount = dto.Amount;
            entity.MeterConsumption = dto.MeterConsumption;
            entity.RPM = dto.RPM;
            entity.Pick = dto.Pick;
            entity.IsDelete = dto.IsDelete;
            entity.IsActive = dto.IsActive;
            entity.CreatedBy = dto.CreatedBy;
            entity.CreationDateTime = dto.CreationDateTime;
            entity.UpdateBy = dto.UpdateBy;
            entity.UpdationDateTime = dto.UpdationDateTime;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tblBeamMST"/> to an instance of <see cref="tblBeamMSTDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tblBeamMST"/> to convert.</param>
        public static tblBeamMSTDTO ToDTO(this tblBeamMST entity)
        {
            if (entity == null) return null;

            var dto = new tblBeamMSTDTO();

            dto.BeemID = entity.BeemID;
            dto.CompanyID = entity.CompanyID;
            dto.WrapperPartyName = entity.WrapperPartyName;
            dto.JobberPartyName = entity.JobberPartyName;
            dto.BeemDate = entity.BeemDate;
            dto.YarnQuality = entity.YarnQuality;
            dto.GrayQuality = entity.GrayQuality;
            dto.TarNo = entity.TarNo;
            dto.Meters = entity.Meters;
            dto.Taka = entity.Taka;
            dto.Weight = entity.Weight;
            dto.ProductionMeters = entity.ProductionMeters;
            dto.ProductionTaka = entity.ProductionTaka;
            dto.PipeWeight = entity.PipeWeight;
            dto.LoadingDate = entity.LoadingDate;
            dto.MinStrategy = entity.MinStrategy;
            dto.MachineNo = entity.MachineNo;
            dto.Remarks = entity.Remarks;
            dto.BhidanStatus = entity.BhidanStatus;
            dto.BhidanDate = entity.BhidanDate;
            dto.PasaraiName = entity.PasaraiName;
            dto.Count = entity.Count;
            dto.IssueDate = entity.IssueDate;
            dto.TakaMeter = entity.TakaMeter;
            dto.Rate = entity.Rate;
            dto.Amount = entity.Amount;
            dto.MeterConsumption = entity.MeterConsumption;
            dto.RPM = entity.RPM;
            dto.Pick = entity.Pick;
            dto.IsDelete = entity.IsDelete;
            dto.IsActive = entity.IsActive;
            dto.CreatedBy = entity.CreatedBy;
            dto.CreationDateTime = entity.CreationDateTime;
            dto.UpdateBy = entity.UpdateBy;
            dto.UpdationDateTime = entity.UpdationDateTime;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tblBeamMSTDTO"/> to an instance of <see cref="tblBeamMST"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tblBeamMST> ToEntities(this IEnumerable<tblBeamMSTDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tblBeamMST"/> to an instance of <see cref="tblBeamMSTDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tblBeamMSTDTO> ToDTOs(this IEnumerable<tblBeamMST> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
