//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-09 - 14:23:58
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using LoomsManagement.Domain.DTO;
using LoomsManagement.DAL.ORM;

namespace LoomsManagement.DAL
{

    /// <summary>
    /// Assembler for <see cref="tblBolierProcessDetail"/> and <see cref="tblBolierProcessDetailDTO"/>.
    /// </summary>
    public static partial class tblBolierProcessDetailAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tblBolierProcessDetailDTO"/> converted from <see cref="tblBolierProcessDetail"/>.</param>
        static partial void OnDTO(this tblBolierProcessDetail entity, tblBolierProcessDetailDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tblBolierProcessDetail"/> converted from <see cref="tblBolierProcessDetailDTO"/>.</param>
        static partial void OnEntity(this tblBolierProcessDetailDTO dto, tblBolierProcessDetail entity);

        /// <summary>
        /// Converts this instance of <see cref="tblBolierProcessDetailDTO"/> to an instance of <see cref="tblBolierProcessDetail"/>.
        /// </summary>
        /// <param name="dto"><see cref="tblBolierProcessDetailDTO"/> to convert.</param>
        public static tblBolierProcessDetail ToEntity(this tblBolierProcessDetailDTO dto)
        {
            if (dto == null) return null;

            var entity = new tblBolierProcessDetail();

            entity.BoilerProcessDetailsID = dto.BoilerProcessDetailsID;
            entity.BoilerProcessID = dto.BoilerProcessID;
            entity.TFORoleProcessID = dto.TFORoleProcessID;
            entity.IssueNoOfTFORoles = dto.IssueNoOfTFORoles;
            entity.IssueWeights = dto.IssueWeights;
            entity.YarnQualityID = dto.YarnQualityID;
            entity.YarnTypeID = dto.YarnTypeID;
            entity.IsDelete = dto.IsDelete;
            entity.CreatedBy = dto.CreatedBy;
            entity.CreatedDateTime = dto.CreatedDateTime;
            entity.UpdatedBy = dto.UpdatedBy;
            entity.UpdatedDateTime = dto.UpdatedDateTime;
            entity.IsActive = dto.IsActive;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tblBolierProcessDetail"/> to an instance of <see cref="tblBolierProcessDetailDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tblBolierProcessDetail"/> to convert.</param>
        public static tblBolierProcessDetailDTO ToDTO(this tblBolierProcessDetail entity)
        {
            if (entity == null) return null;

            var dto = new tblBolierProcessDetailDTO();

            dto.BoilerProcessDetailsID = entity.BoilerProcessDetailsID;
            dto.BoilerProcessID = entity.BoilerProcessID;
            dto.TFORoleProcessID = entity.TFORoleProcessID;
            dto.IssueNoOfTFORoles = entity.IssueNoOfTFORoles;
            dto.IssueWeights = entity.IssueWeights;
            dto.YarnQualityID = entity.YarnQualityID;
            dto.YarnTypeID = entity.YarnTypeID;
            dto.IsDelete = entity.IsDelete;
            dto.CreatedBy = entity.CreatedBy;
            dto.CreatedDateTime = entity.CreatedDateTime;
            dto.UpdatedBy = entity.UpdatedBy;
            dto.UpdatedDateTime = entity.UpdatedDateTime;
            dto.IsActive = entity.IsActive;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tblBolierProcessDetailDTO"/> to an instance of <see cref="tblBolierProcessDetail"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tblBolierProcessDetail> ToEntities(this IEnumerable<tblBolierProcessDetailDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tblBolierProcessDetail"/> to an instance of <see cref="tblBolierProcessDetailDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tblBolierProcessDetailDTO> ToDTOs(this IEnumerable<tblBolierProcessDetail> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
