//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-09 - 14:24:00
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using LoomsManagement.Domain.DTO;
using LoomsManagement.DAL.ORM;

namespace LoomsManagement.DAL
{

    /// <summary>
    /// Assembler for <see cref="tblEmployee"/> and <see cref="tblEmployeeDTO"/>.
    /// </summary>
    public static partial class tblEmployeeAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tblEmployeeDTO"/> converted from <see cref="tblEmployee"/>.</param>
        static partial void OnDTO(this tblEmployee entity, tblEmployeeDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tblEmployee"/> converted from <see cref="tblEmployeeDTO"/>.</param>
        static partial void OnEntity(this tblEmployeeDTO dto, tblEmployee entity);

        /// <summary>
        /// Converts this instance of <see cref="tblEmployeeDTO"/> to an instance of <see cref="tblEmployee"/>.
        /// </summary>
        /// <param name="dto"><see cref="tblEmployeeDTO"/> to convert.</param>
        public static tblEmployee ToEntity(this tblEmployeeDTO dto)
        {
            if (dto == null) return null;

            var entity = new tblEmployee();
            entity.CompanyID = dto.CompanyID;
            entity.EmployeeID = dto.EmployeeID;
            entity.EmployeeTypeID = dto.EmployeeTypeID;
            entity.EmployeeCode = dto.EmployeeCode;
            entity.JobTitle = dto.JobTitle;
            entity.FirstName = dto.FirstName;
            entity.MiddleName = dto.MiddleName;
            entity.LastName = dto.LastName;
            entity.ResidentialAddress = dto.ResidentialAddress;
            entity.PermanentAddress = dto.PermanentAddress;
            entity.MobileNo = dto.MobileNo;
            entity.EmailID = dto.EmailID;
            entity.DOB = dto.DOB;
            entity.Gender = dto.Gender;
            entity.IDProfe = dto.IDProfe;
            entity.IDProfeNo = dto.IDProfeNo;
            entity.Photo = dto.Photo;
            entity.JoinDate = dto.JoinDate;
            entity.LeaveDate = dto.LeaveDate;
            entity.SponsorsID = dto.SponsorsID;
            entity.Shift = dto.Shift;
            entity.Salary = dto.Salary;
            entity.PerDayWorkingHours = dto.PerDayWorkingHours;
            entity.PerHourSalary = dto.PerHourSalary;
            entity.PaymentType = dto.PaymentType;
            entity.BankName = dto.BankName;
            entity.BranchName = dto.BranchName;
            entity.AccountNo = dto.AccountNo;
            entity.RTGSNo = dto.RTGSNo;
            entity.IFSCCode = dto.IFSCCode;
            entity.OpeningBalance = dto.OpeningBalance;
            entity.IsDelete = dto.IsDelete;
            entity.IsActive = dto.IsActive;
            entity.CreatedBY = dto.CreatedBY;
            entity.CreatedDate = dto.CreatedDate;
            entity.UpdatedBy = dto.UpdatedBy;
            entity.UpdatedDate = dto.UpdatedDate;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tblEmployee"/> to an instance of <see cref="tblEmployeeDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tblEmployee"/> to convert.</param>
        public static tblEmployeeDTO ToDTO(this tblEmployee entity)
        {
            if (entity == null) return null;

            var dto = new tblEmployeeDTO();
            dto.CompanyID = entity.CompanyID;
            dto.EmployeeID = entity.EmployeeID;
            dto.EmployeeTypeID = entity.EmployeeTypeID;
            dto.EmployeeCode = entity.EmployeeCode;
            dto.JobTitle = entity.JobTitle;
            dto.FirstName = entity.FirstName;
            dto.MiddleName = entity.MiddleName;
            dto.LastName = entity.LastName;
            dto.ResidentialAddress = entity.ResidentialAddress;
            dto.PermanentAddress = entity.PermanentAddress;
            dto.MobileNo = entity.MobileNo;
            dto.EmailID = entity.EmailID;
            dto.DOB = entity.DOB;
            dto.Gender = entity.Gender;
            dto.IDProfe = entity.IDProfe;
            dto.IDProfeNo = entity.IDProfeNo;
            dto.Photo = entity.Photo;
            dto.JoinDate = entity.JoinDate;
            dto.LeaveDate = entity.LeaveDate;
            dto.SponsorsID = entity.SponsorsID;
            dto.Shift = entity.Shift;
            dto.Salary = entity.Salary;
            dto.PerDayWorkingHours = entity.PerDayWorkingHours;
            dto.PerHourSalary = entity.PerHourSalary;
            dto.PaymentType = entity.PaymentType;
            dto.BankName = entity.BankName;
            dto.BranchName = entity.BranchName;
            dto.AccountNo = entity.AccountNo;
            dto.RTGSNo = entity.RTGSNo;
            dto.IFSCCode = entity.IFSCCode;
            dto.OpeningBalance = entity.OpeningBalance;
            dto.IsDelete = entity.IsDelete;
            dto.IsActive = entity.IsActive;
            dto.CreatedBY = entity.CreatedBY;
            dto.CreatedDate = entity.CreatedDate;
            dto.UpdatedBy = entity.UpdatedBy;
            dto.UpdatedDate = entity.UpdatedDate;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tblEmployeeDTO"/> to an instance of <see cref="tblEmployee"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tblEmployee> ToEntities(this IEnumerable<tblEmployeeDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tblEmployee"/> to an instance of <see cref="tblEmployeeDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tblEmployeeDTO> ToDTOs(this IEnumerable<tblEmployee> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
