//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-09 - 14:24:00
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using LoomsManagement.Domain.DTO;
using LoomsManagement.DAL.ORM;

namespace LoomsManagement.DAL
{

    /// <summary>
    /// Assembler for <see cref="tblEmployeeTypeMST"/> and <see cref="tblEmployeeTypeMSTDTO"/>.
    /// </summary>
    public static partial class tblEmployeeTypeMSTAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tblEmployeeTypeMSTDTO"/> converted from <see cref="tblEmployeeTypeMST"/>.</param>
        static partial void OnDTO(this tblEmployeeTypeMST entity, tblEmployeeTypeMSTDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tblEmployeeTypeMST"/> converted from <see cref="tblEmployeeTypeMSTDTO"/>.</param>
        static partial void OnEntity(this tblEmployeeTypeMSTDTO dto, tblEmployeeTypeMST entity);

        /// <summary>
        /// Converts this instance of <see cref="tblEmployeeTypeMSTDTO"/> to an instance of <see cref="tblEmployeeTypeMST"/>.
        /// </summary>
        /// <param name="dto"><see cref="tblEmployeeTypeMSTDTO"/> to convert.</param>
        public static tblEmployeeTypeMST ToEntity(this tblEmployeeTypeMSTDTO dto)
        {
            if (dto == null) return null;

            var entity = new tblEmployeeTypeMST();

            entity.EmployeeTypeID = dto.EmployeeTypeID;
            entity.TypeName = dto.TypeName;
            entity.Description = dto.Description;
            entity.IsDelete = dto.IsDelete;
            entity.IsActive = dto.IsActive;
            entity.CreatedBy = dto.CreatedBy;
            entity.CreatedDateTime = dto.CreatedDateTime;
            entity.UpdatedBy = dto.UpdatedBy;
            entity.UpdatedDateTime = dto.UpdatedDateTime;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tblEmployeeTypeMST"/> to an instance of <see cref="tblEmployeeTypeMSTDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tblEmployeeTypeMST"/> to convert.</param>
        public static tblEmployeeTypeMSTDTO ToDTO(this tblEmployeeTypeMST entity)
        {
            if (entity == null) return null;

            var dto = new tblEmployeeTypeMSTDTO();

            dto.EmployeeTypeID = entity.EmployeeTypeID;
            dto.TypeName = entity.TypeName;
            dto.Description = entity.Description;
            dto.IsDelete = entity.IsDelete;
            dto.IsActive = entity.IsActive;
            dto.CreatedBy = entity.CreatedBy;
            dto.CreatedDateTime = entity.CreatedDateTime;
            dto.UpdatedBy = entity.UpdatedBy;
            dto.UpdatedDateTime = entity.UpdatedDateTime;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tblEmployeeTypeMSTDTO"/> to an instance of <see cref="tblEmployeeTypeMST"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tblEmployeeTypeMST> ToEntities(this IEnumerable<tblEmployeeTypeMSTDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tblEmployeeTypeMST"/> to an instance of <see cref="tblEmployeeTypeMSTDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tblEmployeeTypeMSTDTO> ToDTOs(this IEnumerable<tblEmployeeTypeMST> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
