//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-31 - 09:13:36
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using LoomsManagement.Domain.DTO;
using LoomsManagement.DAL.ORM;

namespace LoomsManagement.DAL
{

    /// <summary>
    /// Assembler for <see cref="tblFiscalYear"/> and <see cref="tblFiscalYearDTO"/>.
    /// </summary>
    public static partial class tblFiscalYearAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tblFiscalYearDTO"/> converted from <see cref="tblFiscalYear"/>.</param>
        static partial void OnDTO(this tblFiscalYear entity, tblFiscalYearDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tblFiscalYear"/> converted from <see cref="tblFiscalYearDTO"/>.</param>
        static partial void OnEntity(this tblFiscalYearDTO dto, tblFiscalYear entity);

        /// <summary>
        /// Converts this instance of <see cref="tblFiscalYearDTO"/> to an instance of <see cref="tblFiscalYear"/>.
        /// </summary>
        /// <param name="dto"><see cref="tblFiscalYearDTO"/> to convert.</param>
        public static tblFiscalYear ToEntity(this tblFiscalYearDTO dto)
        {
            if (dto == null) return null;

            var entity = new tblFiscalYear();

            entity.FiscalYearId = dto.FiscalYearId;
            entity.FiscalName = dto.FiscalName;
            entity.IsActive = dto.IsActive;
            entity.IsDelete = dto.IsDelete;
            entity.CreatedBy = dto.CreatedBy;
            entity.CreatedDateTime = dto.CreatedDateTime;
            entity.UpdatedBy = dto.UpdatedBy;
            entity.UpdatedDateTime = dto.UpdatedDateTime;
            entity.StartDate = dto.StartDate;
            entity.EndDate = dto.EndDate;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tblFiscalYear"/> to an instance of <see cref="tblFiscalYearDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tblFiscalYear"/> to convert.</param>
        public static tblFiscalYearDTO ToDTO(this tblFiscalYear entity)
        {
            if (entity == null) return null;

            var dto = new tblFiscalYearDTO();

            dto.FiscalYearId = entity.FiscalYearId;
            dto.FiscalName = entity.FiscalName;
            dto.IsActive = entity.IsActive;
            dto.IsDelete = entity.IsDelete;
            dto.CreatedBy = entity.CreatedBy;
            dto.CreatedDateTime = entity.CreatedDateTime;
            dto.UpdatedBy = entity.UpdatedBy;
            dto.UpdatedDateTime = entity.UpdatedDateTime;
            dto.StartDate = entity.StartDate;
            dto.EndDate = entity.EndDate;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tblFiscalYearDTO"/> to an instance of <see cref="tblFiscalYear"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tblFiscalYear> ToEntities(this IEnumerable<tblFiscalYearDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tblFiscalYear"/> to an instance of <see cref="tblFiscalYearDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tblFiscalYearDTO> ToDTOs(this IEnumerable<tblFiscalYear> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
