//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-09 - 14:24:00
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using LoomsManagement.Domain.DTO;
using LoomsManagement.DAL.ORM;

namespace LoomsManagement.DAL
{

    /// <summary>
    /// Assembler for <see cref="tblMachineMST"/> and <see cref="tblMachineMSTDTO"/>.
    /// </summary>
    public static partial class tblMachineMSTAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tblMachineMSTDTO"/> converted from <see cref="tblMachineMST"/>.</param>
        static partial void OnDTO(this tblMachineMST entity, tblMachineMSTDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tblMachineMST"/> converted from <see cref="tblMachineMSTDTO"/>.</param>
        static partial void OnEntity(this tblMachineMSTDTO dto, tblMachineMST entity);

        /// <summary>
        /// Converts this instance of <see cref="tblMachineMSTDTO"/> to an instance of <see cref="tblMachineMST"/>.
        /// </summary>
        /// <param name="dto"><see cref="tblMachineMSTDTO"/> to convert.</param>
        public static tblMachineMST ToEntity(this tblMachineMSTDTO dto)
        {
            if (dto == null) return null;

            var entity = new tblMachineMST();

            entity.MachineID = dto.MachineID;
            entity.MachineName = dto.MachineName;
            entity.MachineTypeID = dto.MachineTypeID;
            entity.AboutMachine = dto.AboutMachine;
            entity.IsDelete = dto.IsDelete;
            entity.IsActive = dto.IsActive;
            entity.CreatedBy = dto.CreatedBy;
            entity.CreatedDateTime = dto.CreatedDateTime;
            entity.UpdatedBy = dto.UpdatedBy;
            entity.UpdatedDateTime = dto.UpdatedDateTime;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tblMachineMST"/> to an instance of <see cref="tblMachineMSTDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tblMachineMST"/> to convert.</param>
        public static tblMachineMSTDTO ToDTO(this tblMachineMST entity)
        {
            if (entity == null) return null;

            var dto = new tblMachineMSTDTO();

            dto.MachineID = entity.MachineID;
            dto.MachineName = entity.MachineName;
            dto.MachineTypeID = entity.MachineTypeID;
            dto.AboutMachine = entity.AboutMachine;
            dto.IsDelete = entity.IsDelete;
            dto.IsActive = entity.IsActive;
            dto.CreatedBy = entity.CreatedBy;
            dto.CreatedDateTime = entity.CreatedDateTime;
            dto.UpdatedBy = entity.UpdatedBy;
            dto.UpdatedDateTime = entity.UpdatedDateTime;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tblMachineMSTDTO"/> to an instance of <see cref="tblMachineMST"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tblMachineMST> ToEntities(this IEnumerable<tblMachineMSTDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tblMachineMST"/> to an instance of <see cref="tblMachineMSTDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tblMachineMSTDTO> ToDTOs(this IEnumerable<tblMachineMST> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
