//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-09 - 14:24:04
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using LoomsManagement.Domain.DTO;
using LoomsManagement.DAL.ORM;

namespace LoomsManagement.DAL
{

    /// <summary>
    /// Assembler for <see cref="tblYarnPurchase"/> and <see cref="tblYarnPurchaseDTO"/>.
    /// </summary>
    public static partial class tblYarnPurchaseAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tblYarnPurchaseDTO"/> converted from <see cref="tblYarnPurchase"/>.</param>
        static partial void OnDTO(this tblYarnPurchase entity, tblYarnPurchaseDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tblYarnPurchase"/> converted from <see cref="tblYarnPurchaseDTO"/>.</param>
        static partial void OnEntity(this tblYarnPurchaseDTO dto, tblYarnPurchase entity);

        /// <summary>
        /// Converts this instance of <see cref="tblYarnPurchaseDTO"/> to an instance of <see cref="tblYarnPurchase"/>.
        /// </summary>
        /// <param name="dto"><see cref="tblYarnPurchaseDTO"/> to convert.</param>
        public static tblYarnPurchase ToEntity(this tblYarnPurchaseDTO dto)
        {
            if (dto == null) return null;

            var entity = new tblYarnPurchase();

            entity.PurchaseID = dto.PurchaseID;
            entity.SRNo = dto.SRNo;
            entity.CompanyID = dto.CompanyID;
            entity.PartyID = dto.PartyID;
            entity.BrokerID = dto.BrokerID;
            entity.YearID = dto.YearID;
            entity.PurchaseDate = dto.PurchaseDate;
            entity.ChallanNo = dto.ChallanNo;
            entity.LRNo = dto.LRNo;
            entity.RecieveAt = dto.RecieveAt;
            entity.Grade = dto.Grade;
            entity.EmployeeId = dto.EmployeeId;
            entity.IsDelete = dto.IsDelete;
            entity.IsDelete_bit_Checked = dto.IsDelete_bit_Checked;
            entity.IsActive = dto.IsActive;
            entity.CreatedBy = dto.CreatedBy;
            entity.CreatedDateTime = dto.CreatedDateTime;
            entity.UpdatedBy = dto.UpdatedBy;
            entity.UpDatedDateTime = dto.UpDatedDateTime;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tblYarnPurchase"/> to an instance of <see cref="tblYarnPurchaseDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tblYarnPurchase"/> to convert.</param>
        public static tblYarnPurchaseDTO ToDTO(this tblYarnPurchase entity)
        {
            if (entity == null) return null;

            var dto = new tblYarnPurchaseDTO();

            dto.PurchaseID = entity.PurchaseID;
            dto.SRNo = entity.SRNo;
            dto.CompanyID = entity.CompanyID;
            dto.PartyID = entity.PartyID;
            dto.BrokerID = entity.BrokerID;
            dto.YearID = entity.YearID;
            dto.PurchaseDate = entity.PurchaseDate;
            dto.ChallanNo = entity.ChallanNo;
            dto.LRNo = entity.LRNo;
            dto.RecieveAt = entity.RecieveAt;
            dto.Grade = entity.Grade;
            dto.EmployeeId = entity.EmployeeId;
            dto.IsDelete = entity.IsDelete;
            dto.IsDelete_bit_Checked = entity.IsDelete_bit_Checked;
            dto.IsActive = entity.IsActive;
            dto.CreatedBy = entity.CreatedBy;
            dto.CreatedDateTime = entity.CreatedDateTime;
            dto.UpdatedBy = entity.UpdatedBy;
            dto.UpDatedDateTime = entity.UpDatedDateTime;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tblYarnPurchaseDTO"/> to an instance of <see cref="tblYarnPurchase"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tblYarnPurchase> ToEntities(this IEnumerable<tblYarnPurchaseDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tblYarnPurchase"/> to an instance of <see cref="tblYarnPurchaseDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tblYarnPurchaseDTO> ToDTOs(this IEnumerable<tblYarnPurchase> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
