//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-09 - 14:24:04
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using LoomsManagement.Domain.DTO;
using LoomsManagement.DAL.ORM;

namespace LoomsManagement.DAL
{

    /// <summary>
    /// Assembler for <see cref="tblYarnPackageType"/> and <see cref="tblYarnPackageTypeDTO"/>.
    /// </summary>
    public static partial class tblYarnPackageTypeAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tblYarnPackageTypeDTO"/> converted from <see cref="tblYarnPackageType"/>.</param>
        static partial void OnDTO(this tblYarnPackageType entity, tblYarnPackageTypeDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tblYarnPackageType"/> converted from <see cref="tblYarnPackageTypeDTO"/>.</param>
        static partial void OnEntity(this tblYarnPackageTypeDTO dto, tblYarnPackageType entity);

        /// <summary>
        /// Converts this instance of <see cref="tblYarnPackageTypeDTO"/> to an instance of <see cref="tblYarnPackageType"/>.
        /// </summary>
        /// <param name="dto"><see cref="tblYarnPackageTypeDTO"/> to convert.</param>
        public static tblYarnPackageType ToEntity(this tblYarnPackageTypeDTO dto)
        {
            if (dto == null) return null;

            var entity = new tblYarnPackageType();

            entity.YarnPackageTypeID = dto.YarnPackageTypeID;
            entity.TypeName = dto.TypeName;
            entity.IsDelete = dto.IsDelete;
            entity.IsActive = dto.IsActive;
            entity.CreatedBy = dto.CreatedBy;
            entity.CreatedDateTime = dto.CreatedDateTime;
            entity.UpdatedBy = dto.UpdatedBy;
            entity.UpdatedDateTime = dto.UpdatedDateTime;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tblYarnPackageType"/> to an instance of <see cref="tblYarnPackageTypeDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tblYarnPackageType"/> to convert.</param>
        public static tblYarnPackageTypeDTO ToDTO(this tblYarnPackageType entity)
        {
            if (entity == null) return null;

            var dto = new tblYarnPackageTypeDTO();

            dto.YarnPackageTypeID = entity.YarnPackageTypeID;
            dto.TypeName = entity.TypeName;
            dto.IsDelete = entity.IsDelete;
            dto.IsActive = entity.IsActive;
            dto.CreatedBy = entity.CreatedBy;
            dto.CreatedDateTime = entity.CreatedDateTime;
            dto.UpdatedBy = entity.UpdatedBy;
            dto.UpdatedDateTime = entity.UpdatedDateTime;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tblYarnPackageTypeDTO"/> to an instance of <see cref="tblYarnPackageType"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tblYarnPackageType> ToEntities(this IEnumerable<tblYarnPackageTypeDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tblYarnPackageType"/> to an instance of <see cref="tblYarnPackageTypeDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tblYarnPackageTypeDTO> ToDTOs(this IEnumerable<tblYarnPackageType> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
